/**
 * Chat API Routes
 * Handles chat functionality with real LLM integration
 * Replaces mock responses with actual AI-powered responses
 */

const express = require('express');
const path = require('path');
const router = express.Router();
const LLMService = require('../services/llm');
const prompts = require('../services/prompts');
const CourseModel = require('../models/Course');
const DocumentModel = require('../models/Document');
const MessageFeedback = require('../models/MessageFeedback');
const ChatSurveyResponse = require('../models/ChatSurveyResponse');
const BadWordsFilter = require('bad-words');
const profanityFilter = new BadWordsFilter();
const TrackerService = require('../services/tracker');
const User = require('../models/User');
const MentalHealthFlag = require('../models/MentalHealthFlag');
const gridfs = require('../services/gridfs');
const { resolveCourseAi, sendLlmKeyError } = require('./llmKeyMiddleware');
const { evaluateObjectiveAnswer } = require('../services/objectiveAnswer');
const { createId } = require('../services/id');

function generateChatMessageId() {
    return createId('msg');
}

function normalizeQdrantSearchResults(results) {
    return Array.isArray(results) ? results : [];
}

/**
 * Determine source attribution based on retrieved chunks
 * @param {Array} searchResults - Array of search results from Qdrant
 * @param {string} unitName - Current unit name
 * @param {boolean} sourceDownloadsEnabled - Whether source document downloads are enabled for the course
 * @returns {Promise<Object>} Source attribution information
 */
/**
 * Determine source attribution based on retrieved chunks
 * @param {Array} searchResults - Array of search results from Qdrant
 * @param {string} unitName - Current unit name
 * @param {boolean} sourceDownloadsEnabled - Whether source document downloads are enabled for the course
 * @returns {Promise<Object>} Source attribution information
 */
async function determineSourceAttribution(searchResults, unitName, sourceDownloadsEnabled = false) {
    try {
        // If no search results, content is from GPT
        if (!searchResults || searchResults.length === 0) {
            return {
                source: 'GPT',
                description: 'Generated by AI (no relevant course materials found)',
                unitName: null,
                documentType: null,
                downloadsEnabled: false,
                documents: []
            };
        }

        // Check if search results are relevant enough (low scores indicate poor matches)
        const scores = searchResults.map(result => (result.score || 0));
        const maxScore = Math.max(...scores);
        const top3Scores = [...scores].sort((a, b) => b - a).slice(0, 3);
        const avgTop3Score = top3Scores.length > 0
            ? top3Scores.reduce((sum, score) => sum + score, 0) / top3Scores.length
            : 0;

        console.log('🔍 [SOURCE_DEBUG] Search relevance - avgTop3Score:', avgTop3Score, 'maxScore:', maxScore);

        // Treat as GPT only when both max and top-hit average are weak.
        if (avgTop3Score < 0.10 && maxScore < 0.18) {
            console.log('🔍 [SOURCE_DEBUG] Low relevance scores - treating as GPT');
            return {
                source: 'GPT',
                description: 'Generated by AI (no relevant course materials found)',
                unitName: null,
                documentType: null,
                downloadsEnabled: false,
                documents: []
            };
        }

        // Filter for meaningful chunks
        const relevantChunks = searchResults.filter(result => (result.score || 0) > 0.10);

        if (relevantChunks.length === 0) {
             return {
                source: 'GPT',
                description: 'Generated by AI (no relevant course materials found)',
                unitName: null,
                documentType: null,
                downloadsEnabled: false,
                documents: []
            };
        }

        // Collect unique sources
        const sources = new Set();
        const sourceDocuments = new Map();
        
        relevantChunks.forEach(chunk => {
            const docType = chunk.type || chunk.documentType || 'unknown';
            const sourceUnit = chunk.lectureName || unitName;
            const score = typeof chunk.score === 'number' ? chunk.score : 0;
            
            let readableType = 'Material';
            switch (docType) {
                case 'lecture_notes': readableType = 'Lecture Notes'; break;
                case 'practice_q_tutorials':
                case 'practice-quiz':
                    readableType = 'Practice Questions';
                    break;
                case 'additional': readableType = 'Additional Materials'; break;
                default: readableType = 'Course Material';
            }

            sources.add(`${readableType} (${sourceUnit})`);

            const rawDocumentId = typeof chunk.documentId === 'string' ? chunk.documentId.trim() : '';
            const documentId = rawDocumentId || null;
            // Deduplicate by type + unit (not fileName, which is inconsistent across chunks)
            const dedupeKey = `${readableType}::${sourceUnit}`;
            const existing = sourceDocuments.get(dedupeKey);

            if (!existing) {
                sourceDocuments.set(dedupeKey, {
                    documentId,
                    fileName: readableType,
                    lectureName: sourceUnit || unitName || null,
                    maxScore: score
                });
            } else {
                if (score > existing.maxScore) {
                    existing.maxScore = score;
                    // Prefer documentId from highest-scoring chunk (most likely the newest valid upload)
                    if (documentId) {
                        existing.documentId = documentId;
                    }
                } else if (!existing.documentId && documentId) {
                    existing.documentId = documentId;
                }
            }
        });

        // Debug: Log details about practice quiz chunks specifically
        const practiceQuizChunks = searchResults.filter(r => r.type === 'practice_q_tutorials' || r.documentType === 'practice-quiz');
        if (practiceQuizChunks.length > 0) {
            console.log('🔍 [SOURCE_DEBUG] Practice quiz chunks found:', practiceQuizChunks.length);
        }

        const sortedSourceDocs = Array.from(sourceDocuments.values())
            .sort((a, b) => b.maxScore - a.maxScore);
        const sourceDescription = sortedSourceDocs.length > 0
            ? sortedSourceDocs
                .map(doc => `${doc.fileName}${doc.lectureName ? ` (${doc.lectureName})` : ''}`)
                .join(', ')
            : Array.from(sources).join(', ');
        console.log('🔍 [SOURCE_DEBUG] Final Source Description:', sourceDescription);

        const downloadableDocuments = sortedSourceDocs
            .filter(doc => !!doc.documentId)
            .map(doc => ({
                documentId: doc.documentId,
                fileName: doc.fileName,
                lectureName: doc.lectureName
            }));

        return {
            source: 'multiple',
            description: `From: ${sourceDescription || 'Course Material'}`,
            unitName: unitName,
            documentType: 'multiple',
            downloadsEnabled: !!sourceDownloadsEnabled,
            documents: sourceDownloadsEnabled ? downloadableDocuments : []
        };

    } catch (error) {
        console.error('Error determining source attribution:', error);
        return {
            source: 'GPT',
            description: 'Generated by AI (error determining source)',
            unitName: null,
            documentType: null,
            downloadsEnabled: false,
            documents: []
        };
    }
}

function inferExtensionFromMimeType(mimeType) {
    switch ((mimeType || '').toLowerCase()) {
        case 'application/pdf':
            return '.pdf';
        case 'text/markdown':
            return '.md';
        case 'application/msword':
            return '.doc';
        case 'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
            return '.docx';
        case 'application/vnd.openxmlformats-officedocument.presentationml.presentation':
            return '.pptx';
        case 'application/rtf':
            return '.rtf';
        case 'text/plain':
            return '.txt';
        default:
            return '';
    }
}

function resolveDownloadFilename(document) {
    const fallbackName = `source-${document.documentId || Date.now()}`;
    const rawOriginal = (document.originalName || '').trim();
    const rawFile = (document.filename || '').trim();
    const preferredName = rawOriginal || rawFile || fallbackName;
    let safeName = path.basename(preferredName).replace(/[\r\n]/g, '');

    if (!path.extname(safeName)) {
        if (rawFile && path.extname(rawFile)) {
            safeName = path.basename(rawFile).replace(/[\r\n]/g, '');
        } else {
            safeName += inferExtensionFromMimeType(document.mimeType);
        }
    }

    return safeName || `${fallbackName}.txt`;
}

function setAttachmentHeaders(res, filename) {
    const encodedName = encodeURIComponent(filename);
    const asciiFallback = filename.replace(/[^\x20-\x7E]/g, '_').replace(/"/g, '');
    res.setHeader(
        'Content-Disposition',
        `attachment; filename="${asciiFallback}"; filename*=UTF-8''${encodedName}`
    );
}

/**
 * Analyze chunk sources to determine document types
 * @param {Array} searchResults - Array of search results
 * @returns {Object} Analysis of chunk sources
 */
function analyzeChunkSources(searchResults) {
    const analysis = {
        hasLectureNotes: false,
        hasAdditionalMaterials: false,
        hasPracticeQuiz: false,
        hasUnknownType: false
    };

    for (const result of searchResults) {
        const docType = result.type || result.documentType || 'unknown';
        console.log('🔍 [SOURCE_DEBUG] Analyzing chunk with docType:', docType, 'fileName:', result.fileName);

        switch (docType) {
            case 'lecture_notes':
                analysis.hasLectureNotes = true;
                break;
            case 'additional':
                analysis.hasAdditionalMaterials = true;
                break;
            case 'practice_q_tutorials':
                analysis.hasPracticeQuiz = true;
                break;
            case 'unknown':
                analysis.hasUnknownType = true;
                // Try to infer type from filename for legacy documents
                const fileName = (result.fileName || '').toLowerCase();
                console.log('🔍 [SOURCE_DEBUG] Inferring type from filename:', fileName);

                // Be more specific about lecture notes inference
                if (fileName.includes('lecture') && (fileName.includes('notes') || fileName.includes('note'))) {
                    analysis.hasLectureNotes = true;
                } else if (fileName.includes('practice') || fileName.includes('quiz') || fileName.includes('tutorial')) {
                    analysis.hasPracticeQuiz = true;
                } else {
                    // Default to additional materials for unknown types
                    analysis.hasAdditionalMaterials = true;
                }
                break;
        }
    }

    return analysis;
}

// Middleware to parse JSON bodies
router.use(express.json());

function parseBooleanQuery(value) {
    return value === true || value === 'true' || value === '1';
}

async function canReadCourseFeedback(db, user, courseId) {
    if (!user || (user.role !== 'instructor' && user.role !== 'ta')) {
        return false;
    }

    const hasCourseAccess = await CourseModel.userHasCourseAccess(db, courseId, user.userId, user.role);
    if (!hasCourseAccess) return false;

    if (user.role === 'ta') {
        return CourseModel.checkTAPermission(db, courseId, user.userId, 'flags');
    }

    return true;
}

async function canCreateFeedbackForCourse(db, user, courseId) {
    if (!user || user.role !== 'student') {
        return false;
    }

    const enrollment = await CourseModel.getStudentEnrollment(db, courseId, user.userId);
    return !!(enrollment.success && enrollment.enrolled);
}

const SUMMARY_MAX_MESSAGES = 80;
const SUMMARY_MAX_MESSAGE_CHARS = 2000;
const SUMMARY_MAX_TOTAL_CHARS = 20000;
const SUMMARY_MAX_PROMPT_CHARS = 8000;

function normalizeSummaryContent(content) {
    return String(content || '')
        .replace(/<script[\s\S]*?<\/script>/gi, ' ')
        .replace(/<style[\s\S]*?<\/style>/gi, ' ')
        .replace(/<[^>]+>/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();
}

function normalizeSummaryMessages(messages = []) {
    if (!Array.isArray(messages)) return [];

    const normalized = messages
        .filter((message) => {
            if (!message || typeof message !== 'object') return false;
            if (message.isSummarySeed === true) return false;
            if (message.messageType && message.messageType !== 'regular-chat') return false;
            const type = message.type || message.role;
            return type === 'user' || type === 'student' || type === 'bot' || type === 'assistant';
        })
        .map((message) => {
            const type = message.type || message.role;
            const role = type === 'bot' || type === 'assistant' ? 'bot' : 'student';
            const content = normalizeSummaryContent(message.content || message.message || message.text);
            return {
                role,
                content: content.slice(0, SUMMARY_MAX_MESSAGE_CHARS)
            };
        })
        .filter((message) => message.content);

    const recentMessages = normalized.slice(-SUMMARY_MAX_MESSAGES);
    const bounded = [];
    let totalChars = 0;

    for (let index = recentMessages.length - 1; index >= 0; index -= 1) {
        const message = recentMessages[index];
        if (totalChars + message.content.length > SUMMARY_MAX_TOTAL_CHARS && bounded.length > 0) {
            break;
        }
        bounded.unshift(message);
        totalChars += message.content.length;
    }

    return bounded;
}

function resolveChatSummaryInstructions(course) {
    const coursePrompt = course
        && course.prompts
        && typeof course.prompts.chatSummary === 'string'
        ? course.prompts.chatSummary.trim()
        : '';
    return (coursePrompt || prompts.DEFAULT_PROMPTS.chatSummary).slice(0, SUMMARY_MAX_PROMPT_CHARS);
}

function buildChatSummaryPrompt({ messages, unitName, mode, instructions }) {
    const transcript = messages
        .map((message) => `${message.role === 'student' ? 'Student' : 'BiocBot'}: ${message.content}`)
        .join('\n\n');
    const promptInstructions = String(instructions || prompts.DEFAULT_PROMPTS.chatSummary).trim()
        || prompts.DEFAULT_PROMPTS.chatSummary;

    return `${promptInstructions}

Context:
- Unit: ${unitName}
- Bot mode to preserve: ${mode === 'protege' ? 'protege' : 'tutor'}

Transcript:
${transcript}`;
}

/**
 * POST /api/chat/feedback
 * Upsert or clear thumbs-up / thumbs-down feedback for an assistant message.
 */
router.post('/feedback', async (req, res) => {
    try {
        const user = req.user;
        if (!user) {
            return res.status(401).json({ success: false, message: 'Authentication required' });
        }
        if (user.role !== 'student') {
            return res.status(403).json({ success: false, message: 'Only students can submit chat feedback' });
        }

        const {
            courseId,
            unitName,
            conversationId,
            messageId,
            rating,
            botMode,
            messageContent,
            sourceAttribution
        } = req.body;

        if (!Object.prototype.hasOwnProperty.call(req.body, 'rating')) {
            return res.status(400).json({ success: false, message: 'rating is required' });
        }

        const normalizedRating = MessageFeedback.normalizeRating(rating);
        if (normalizedRating === undefined) {
            return res.status(400).json({ success: false, message: 'rating must be "up", "down", or null' });
        }

        const db = req.app.locals.db;
        if (!db) {
            return res.status(503).json({ success: false, message: 'Database connection not available' });
        }

        if (!courseId || !conversationId || !messageId) {
            return res.status(400).json({
                success: false,
                message: 'courseId, conversationId, and messageId are required'
            });
        }

        const course = await CourseModel.getCourseById(db, courseId);
        if (!course) {
            return res.status(404).json({ success: false, message: 'Course not found' });
        }

        const hasAccess = await canCreateFeedbackForCourse(db, user, courseId);
        if (!hasAccess) {
            return res.status(403).json({ success: false, message: 'No access to submit feedback for this course' });
        }

        const result = await MessageFeedback.upsertMessageFeedback(db, {
            courseId,
            unitName,
            conversationId,
            messageId,
            rating,
            studentId: user.userId,
            studentName: user.displayName || user.username || user.userId,
            botMode,
            messageContent,
            sourceAttribution
        });

        if (!result.success) {
            return res.status(400).json({ success: false, message: result.error || 'Failed to save feedback' });
        }

        return res.json({
            success: true,
            message: result.feedback.isActive ? 'Feedback saved' : 'Feedback cleared',
            data: { feedback: result.feedback }
        });
    } catch (error) {
        console.error('Error saving chat message feedback:', error);
        return res.status(500).json({ success: false, message: 'Internal server error while saving feedback' });
    }
});

/**
 * POST /api/chat/summary
 * Summarize an existing student/BiocBot chat so it can seed a fresh session.
 */
router.post('/summary', async (req, res) => {
    try {
        const user = req.user;
        if (!user) {
            return res.status(401).json({ success: false, message: 'Authentication required' });
        }
        if (user.role !== 'student') {
            return res.status(403).json({ success: false, message: 'Only students can summarize chat sessions' });
        }

        const { courseId, unitName, mode, messages } = req.body;
        if (!courseId || !unitName) {
            return res.status(400).json({ success: false, message: 'courseId and unitName are required' });
        }

        const db = req.app.locals.db;
        if (!db) {
            return res.status(503).json({ success: false, message: 'Database connection not available' });
        }

        const course = await db.collection('courses').findOne({ courseId });
        if (!course) {
            return res.status(404).json({ success: false, message: 'Course not found' });
        }

        const canSummarize = await canCreateFeedbackForCourse(db, user, courseId);
        if (!canSummarize) {
            return res.status(403).json({ success: false, message: 'No access to summarize chats for this course' });
        }

        const publishedUnits = (course.lectures || []).filter(unit => unit.isPublished).map(unit => unit.name);
        if (!publishedUnits.includes(unitName)) {
            return res.status(400).json({ success: false, message: 'Selected unit is not published or does not exist' });
        }

        const summaryMessages = normalizeSummaryMessages(messages);
        const hasStudentMessage = summaryMessages.some(message => message.role === 'student');
        const hasBotMessage = summaryMessages.some(message => message.role === 'bot');
        if (!hasStudentMessage || !hasBotMessage) {
            return res.status(400).json({
                success: false,
                message: 'At least one student message and one BiocBot message are required to summarize a chat'
            });
        }

        const ai = await resolveCourseAi(req, res, courseId);
        if (!ai) return;

        const summaryPrompt = buildChatSummaryPrompt({
            messages: summaryMessages,
            unitName,
            mode,
            instructions: resolveChatSummaryInstructions(course)
        });

        const response = await ai.llm.sendMessage(summaryPrompt, {
            temperature: 0.2,
            maxTokens: 700,
            systemPrompt: 'You summarize tutoring conversations for continuity. Return only the student-voice summary.'
        });

        const summary = normalizeSummaryContent(response && response.content);
        if (!summary) {
            return res.status(502).json({ success: false, message: 'Failed to generate a chat summary' });
        }

        return res.json({
            success: true,
            summary,
            message: summary,
            mode: mode === 'protege' ? 'protege' : 'tutor',
            unitName,
            sourceMessageCount: summaryMessages.length,
            timestamp: new Date().toISOString()
        });
    } catch (error) {
        console.error('Error summarizing chat session:', error);
        return res.status(500).json({
            success: false,
            message: 'Internal server error while summarizing chat session'
        });
    }
});

/**
 * GET /api/chat/survey-settings
 * Return the student-facing chat survey settings for an enrolled student.
 */
router.get('/survey-settings', async (req, res) => {
    try {
        const user = req.user;
        if (!user) {
            return res.status(401).json({ success: false, message: 'Authentication required' });
        }
        if (user.role !== 'student') {
            return res.status(403).json({ success: false, message: 'Only students can access chat survey settings' });
        }

        const { courseId, conversationId } = req.query;
        if (!courseId) {
            return res.status(400).json({ success: false, message: 'courseId is required' });
        }

        const db = req.app.locals.db;
        if (!db) {
            return res.status(503).json({ success: false, message: 'Database connection not available' });
        }

        const settingsResult = await CourseModel.getChatSurveySettings(db, courseId);
        if (!settingsResult.success) {
            return res.status(404).json({ success: false, message: settingsResult.error || 'Course not found' });
        }

        const hasAccess = await canCreateFeedbackForCourse(db, user, courseId);
        if (!hasAccess) {
            return res.status(403).json({ success: false, message: 'No access to this course survey' });
        }

        const settingsFingerprint = ChatSurveyResponse.buildSettingsFingerprint(settingsResult.settings);
        let response = null;
        if (conversationId) {
            response = await ChatSurveyResponse.getSurveyResponseForSession(db, {
                courseId,
                studentId: user.userId,
                conversationId,
                settingsFingerprint
            });
        }

        return res.json({
            success: true,
            data: {
                courseId,
                settings: settingsResult.settings,
                defaults: settingsResult.defaults,
                settingsFingerprint,
                response
            }
        });
    } catch (error) {
        console.error('Error fetching student chat survey settings:', error);
        return res.status(500).json({ success: false, message: 'Internal server error while retrieving survey settings' });
    }
});

/**
 * POST /api/chat/survey
 * Record that a student saw, dismissed, or submitted the session survey.
 */
router.post('/survey', async (req, res) => {
    try {
        const user = req.user;
        if (!user) {
            return res.status(401).json({ success: false, message: 'Authentication required' });
        }
        if (user.role !== 'student') {
            return res.status(403).json({ success: false, message: 'Only students can submit chat surveys' });
        }

        const {
            courseId,
            unitName,
            conversationId,
            eventType,
            ratingAccuracy,
            ratingSatisfaction,
            comment,
            messageCountAtPrompt,
            botMode,
            settingsFingerprint: suppliedSettingsFingerprint
        } = req.body;

        if (!courseId || !conversationId || !eventType) {
            return res.status(400).json({
                success: false,
                message: 'courseId, conversationId, and eventType are required'
            });
        }

        const db = req.app.locals.db;
        if (!db) {
            return res.status(503).json({ success: false, message: 'Database connection not available' });
        }

        const settingsResult = await CourseModel.getChatSurveySettings(db, courseId);
        if (!settingsResult.success) {
            return res.status(404).json({ success: false, message: settingsResult.error || 'Course not found' });
        }

        const hasAccess = await canCreateFeedbackForCourse(db, user, courseId);
        if (!hasAccess) {
            return res.status(403).json({ success: false, message: 'No access to submit surveys for this course' });
        }

        const settings = settingsResult.settings;
        if (!settings.enabled) {
            return res.status(400).json({ success: false, message: 'Chat survey is not enabled for this course' });
        }

        const settingsFingerprint = ChatSurveyResponse.buildSettingsFingerprint(settings);
        if (suppliedSettingsFingerprint && suppliedSettingsFingerprint !== settingsFingerprint) {
            return res.status(409).json({
                success: false,
                message: 'Chat survey settings changed. Please refresh and try again.'
            });
        }

        const result = await ChatSurveyResponse.upsertChatSurveyEvent(db, {
            courseId,
            unitName,
            conversationId,
            eventType,
            ratingAccuracy,
            ratingSatisfaction,
            comment,
            messageCountAtPrompt,
            botMode,
            settings,
            settingsFingerprint,
            studentId: user.userId,
            studentName: user.displayName || user.username || user.userId
        });

        if (!result.success) {
            return res.status(400).json({ success: false, message: result.error || 'Failed to save survey response' });
        }

        return res.json({
            success: true,
            message: 'Survey response saved',
            data: { response: result.response }
        });
    } catch (error) {
        console.error('Error saving chat survey response:', error);
        return res.status(500).json({ success: false, message: 'Internal server error while saving survey response' });
    }
});

/**
 * GET /api/chat/feedback/course/:courseId
 * List message feedback for instructor/TA review.
 */
router.get('/feedback/course/:courseId', async (req, res) => {
    try {
        const { courseId } = req.params;
        const db = req.app.locals.db;
        if (!db) {
            return res.status(503).json({ success: false, message: 'Database connection not available' });
        }

        const hasAccess = await canReadCourseFeedback(db, req.user, courseId);
        if (!hasAccess) {
            return res.status(403).json({ success: false, message: 'No access to feedback for this course' });
        }

        const options = {
            includeCleared: parseBooleanQuery(req.query.includeCleared),
            rating: req.query.rating,
            studentId: req.query.studentId,
            conversationId: req.query.conversationId,
            limit: Number.parseInt(req.query.limit, 10)
        };

        const [feedback, stats] = await Promise.all([
            MessageFeedback.listFeedbackForCourse(db, courseId, options),
            MessageFeedback.getFeedbackStatsForCourse(db, courseId)
        ]);

        return res.json({
            success: true,
            data: {
                courseId,
                feedback,
                count: feedback.length,
                stats
            }
        });
    } catch (error) {
        console.error('Error listing chat message feedback:', error);
        return res.status(500).json({ success: false, message: 'Internal server error while retrieving feedback' });
    }
});

/**
 * GET /api/chat/feedback/course/:courseId/export
 * Export message feedback as CSV for instructor/TA review.
 */
router.get('/feedback/course/:courseId/export', async (req, res) => {
    try {
        const { courseId } = req.params;
        const db = req.app.locals.db;
        if (!db) {
            return res.status(503).json({ success: false, message: 'Database connection not available' });
        }

        const hasAccess = await canReadCourseFeedback(db, req.user, courseId);
        if (!hasAccess) {
            return res.status(403).json({ success: false, message: 'No access to feedback for this course' });
        }

        const feedback = await MessageFeedback.listFeedbackForCourse(db, courseId, {
            includeCleared: true,
            rating: req.query.rating,
            studentId: req.query.studentId,
            conversationId: req.query.conversationId,
            limit: Number.parseInt(req.query.limit, 10) || 1000
        });

        const csv = MessageFeedback.feedbackToCsv(feedback);
        const safeCourseId = String(courseId).replace(/[^A-Za-z0-9_-]/g, '_');
        res.setHeader('Content-Type', 'text/csv; charset=utf-8');
        res.setHeader('Content-Disposition', `attachment; filename="message-feedback-${safeCourseId}.csv"`);
        return res.send(csv);
    } catch (error) {
        console.error('Error exporting chat message feedback:', error);
        return res.status(500).json({ success: false, message: 'Internal server error while exporting feedback' });
    }
});

/**
 * GET /api/chat/survey/course/:courseId
 * List chat survey responses for instructor/TA review.
 */
router.get('/survey/course/:courseId', async (req, res) => {
    try {
        const { courseId } = req.params;
        const db = req.app.locals.db;
        if (!db) {
            return res.status(503).json({ success: false, message: 'Database connection not available' });
        }

        const hasAccess = await canReadCourseFeedback(db, req.user, courseId);
        if (!hasAccess) {
            return res.status(403).json({ success: false, message: 'No access to survey responses for this course' });
        }

        const options = {
            status: req.query.status,
            studentId: req.query.studentId,
            conversationId: req.query.conversationId,
            limit: Number.parseInt(req.query.limit, 10)
        };

        const [responses, stats] = await Promise.all([
            ChatSurveyResponse.listSurveyResponsesForCourse(db, courseId, options),
            ChatSurveyResponse.getSurveyStatsForCourse(db, courseId)
        ]);

        return res.json({
            success: true,
            data: {
                courseId,
                responses,
                count: responses.length,
                stats
            }
        });
    } catch (error) {
        console.error('Error listing chat survey responses:', error);
        return res.status(500).json({ success: false, message: 'Internal server error while retrieving survey responses' });
    }
});

/**
 * GET /api/chat/survey/course/:courseId/export
 * Export chat survey responses as CSV for instructor/TA review.
 */
router.get('/survey/course/:courseId/export', async (req, res) => {
    try {
        const { courseId } = req.params;
        const db = req.app.locals.db;
        if (!db) {
            return res.status(503).json({ success: false, message: 'Database connection not available' });
        }

        const hasAccess = await canReadCourseFeedback(db, req.user, courseId);
        if (!hasAccess) {
            return res.status(403).json({ success: false, message: 'No access to survey responses for this course' });
        }

        const responses = await ChatSurveyResponse.listSurveyResponsesForCourse(db, courseId, {
            status: req.query.status,
            studentId: req.query.studentId,
            conversationId: req.query.conversationId,
            limit: Number.parseInt(req.query.limit, 10) || 1000
        });

        const csv = ChatSurveyResponse.surveyResponsesToCsv(responses);
        const safeCourseId = String(courseId).replace(/[^A-Za-z0-9_-]/g, '_');
        res.setHeader('Content-Type', 'text/csv; charset=utf-8');
        res.setHeader('Content-Disposition', `attachment; filename="chat-survey-responses-${safeCourseId}.csv"`);
        return res.send(csv);
    } catch (error) {
        console.error('Error exporting chat survey responses:', error);
        return res.status(500).json({ success: false, message: 'Internal server error while exporting survey responses' });
    }
});

/**
 * GET /api/chat/source-documents/:documentId/download
 * Download a source-attributed document when enabled for the course
 */
router.get('/source-documents/:documentId/download', async (req, res) => {
    try {
        const { documentId } = req.params;
        const { courseId } = req.query;

        if (!documentId || !courseId) {
            return res.status(400).json({ success: false, message: 'Missing documentId or courseId' });
        }

        const user = req.user;
        if (!user) {
            return res.status(401).json({ success: false, message: 'Authentication required' });
        }

        const db = req.app.locals.db;
        if (!db) {
            return res.status(503).json({ success: false, message: 'Database connection not available' });
        }

        const course = await db.collection('courses').findOne(
            { courseId },
            { projection: { courseId: 1, quizSettings: 1 } }
        );
        if (!course) {
            return res.status(404).json({ success: false, message: 'Course not found' });
        }

        const downloadsEnabled = !!(course.quizSettings && course.quizSettings.allowSourceAttributionDownloads);
        if (!downloadsEnabled) {
            return res.status(403).json({ success: false, message: 'Source attribution downloads are not enabled for this course' });
        }

        let hasAccess = false;
        if (user.role === 'student') {
            const enrollment = await CourseModel.getStudentEnrollment(db, courseId, user.userId);
            hasAccess = !!(enrollment.success && enrollment.enrolled);
        } else if (user.role === 'instructor' || user.role === 'ta') {
            hasAccess = await CourseModel.userHasCourseAccess(db, courseId, user.userId, user.role);
        }

        if (!hasAccess) {
            return res.status(403).json({ success: false, message: 'Access denied for this course' });
        }

        const document = await DocumentModel.getDocumentById(db, documentId);
        if (!document || document.courseId !== courseId) {
            return res.status(404).json({ success: false, message: 'Document not found' });
        }

        const downloadFilename = resolveDownloadFilename(document);
        setAttachmentHeaders(res, downloadFilename);

        const isFileDocument = document.contentType === 'file'
            || ((!!document.fileData || !!document.fileId) && document.contentType !== 'text');

        if (isFileDocument) {
            // Newer uploads keep the binary in GridFS (referenced by fileId); older
            // documents may still have it inline in fileData. Support both so the
            // student gets the original file (e.g. the full PowerPoint), not the
            // extracted text.
            if (document.fileId) {
                res.setHeader('Content-Type', document.mimeType || 'application/octet-stream');
                return gridfs.openDownloadStream(db, document.fileId)
                    .on('error', (err) => {
                        console.error(`❌ GridFS download failed for source document ${documentId}:`, err.message);
                        if (!res.headersSent) {
                            res.status(500).json({ success: false, message: 'Stored file could not be read' });
                        } else {
                            res.end();
                        }
                    })
                    .pipe(res);
            }

            const payload = Buffer.isBuffer(document.fileData)
                ? document.fileData
                : (document.fileData && document.fileData.buffer ? Buffer.from(document.fileData.buffer) : null);

            if (!payload) {
                return res.status(500).json({ success: false, message: 'Stored file data is invalid' });
            }

            res.setHeader('Content-Type', document.mimeType || 'application/octet-stream');
            return res.send(payload);
        }

        const textContent = typeof document.content === 'string' ? document.content : '';
        res.setHeader('Content-Type', `${document.mimeType || 'text/plain'}; charset=utf-8`);
        return res.send(textContent);
    } catch (error) {
        console.error('Error downloading source-attributed document:', error);
        res.status(500).json({ success: false, message: 'Failed to download source document' });
    }
});

/**
 * POST /api/chat
 * Send a message to the LLM and get a response
 */
router.post('/', async (req, res) => {
    try {
        console.log('🔥 [CHAT_ROUTE_HIT] Processing POST /api/chat');
        console.log('💬 [CHAT_API] New chat request received');
        console.log('💬 [CHAT_API] Message:', req.body.message?.substring(0, 50) + '...');
        console.log('💬 [CHAT_API] Has conversationContext:', !!req.body.conversationContext);
        console.log('🔐 [CHAT_API] Auth check - Cookie present:', !!req.headers.cookie);
        console.log('🔐 [CHAT_API] Auth check - User present:', !!req.user);

        let llmService = null;
        let qdrant = null;

        const { message, conversationId, mode, unitName, courseId, conversationContext } = req.body;

        // Get DB connection early
        const db = req.app.locals.db;
        if (!db) {
            return res.status(503).json({ success: false, message: 'Database connection not available' });
        }


        // Validate required fields
        if (!message || typeof message !== 'string') {
            return res.status(400).json({
                success: false,
                message: 'Message is required and must be a string'
            });
        }

        console.log(`💬 Chat request received: "${message.substring(0, 50)}..."`);
        console.log(`🎯 Mode: ${mode || 'default'}`);

        // Require courseId and unitName per requirements
        if (!courseId || !unitName) {
            return res.status(400).json({
                success: false,
                message: 'courseId and unitName are required to start chat'
            });
        }

        // Profanity filter: intercept before any RAG/GPT work to save tokens
        // If the cleaned text differs from the original, return a warning response
        // Skip for explanation requests (system generated from valid bot content)
        if (!req.body.isExplanationRequest) {
            const cleanedMessage = profanityFilter.clean(message);

            if (cleanedMessage !== message) {
            const warningText = 'please watch the language, this is a tool and this data will be used for internal and data analysis';
            console.log('⚠️ [CHAT_API] Profanity detected. Returning warning without querying LLM.');
            return res.json({
                success: true,
                messageId: generateChatMessageId(),
                message: warningText,
                model: 'system',
                usage: { tokens: 0 },
                timestamp: new Date().toISOString(),
                mode: mode || 'default',
                citations: [],
                sourceAttribution: {
                    source: 'system',
                    description: 'Profanity filtered warning',
                    unitName: null,
                    documentType: null,
                    downloadsEnabled: false,
                    documents: []
                },
                debug: {
                    profanityFiltered: true
                },
                retrieval: {
                    mode: 'n/a',
                    lectureNames: []
                }

            });
        }
    }
        
        
        // Mental health detection is handled by the parallel LLM detection (fire-and-forget)
        // The chat bot's mode prompts include SAFETY PROTOCOL to provide the wellness link directly

        // Load course early (used by both struggle mapping and retrieval config)
        const coursesCol = db.collection('courses');
        const course = await coursesCol.findOne({ courseId });
        if (!course) {
            return res.status(404).json({ success: false, message: 'Course not found' });
        }

        const ai = await resolveCourseAi(req, res, courseId);
        if (!ai) return;
        llmService = ai.llm;
        qdrant = ai.qdrant;

        const approvedStruggleTopics = CourseModel.normalizeTopicList(course.approvedStruggleTopics || []);
        console.log(`🧭 [CHAT_TOPIC_MAP] Approved topics loaded: ${approvedStruggleTopics.length}`);

        // STRUGGLE DETECTION & TRACKING
        let struggleState = null;
        let directiveModeActive = false;
        let identifiedTopic = null;

        const appLLM = llmService;
        const trackerService = appLLM ? new TrackerService(appLLM) : null;

        console.log(`🕵️ [CHAT_API_DEBUG] User Context: ID=${req.user ? req.user.userId : 'MISSING'}, Tracker=${!!trackerService}`);

        if (req.user && trackerService) {
            try {
                // Check if this is an explanation request with a known topic
                // If so, we can skip analysis and directly increment struggle for that topic
                if (req.body.isExplanationRequest && req.body.topic) {
                     const explanationTopic = String(req.body.topic || '').trim();
                     const matchedApprovedTopic = approvedStruggleTopics.find(
                        topic => topic.toLowerCase() === explanationTopic.toLowerCase()
                     );

                     if (!matchedApprovedTopic) {
                        console.log(`🕵️ [CHAT_API_DEBUG] Explanation topic "${explanationTopic}" is not approved; skipping struggle update.`);
                     } else {
                        console.log(`🕵️ [CHAT_API_DEBUG] Explanation Request for approved topic: "${matchedApprovedTopic}" - Incrementing Struggle Count`);

                        const updateResult = await User.updateUserStruggleState(db, req.user.userId, {
                            topic: matchedApprovedTopic,
                            isStruggling: true,
                            reason: 'User requested explanation'
                        }, courseId);

                        console.log('🕵️ [CHAT_API_DEBUG] Struggle Update (Explain) Result:', JSON.stringify(updateResult, null, 2));

                        if (updateResult.success && !updateResult.skipped) {
                            struggleState = updateResult.state; // topic specific state
                            identifiedTopic = matchedApprovedTopic;

                            // We also need the full state to determine if ANY directive mode is active
                            // But updateUserStruggleState returns { success, state, allTopics }
                            // Let's verify if *this* topic triggered directive mode
                            if (struggleState && struggleState.isActive) {
                                directiveModeActive = true;
                                console.log(`🚨 [CHAT_API_DEBUG] Directive Mode ACTIVATED via Explain for topic: ${identifiedTopic}`);
                            }
                        }
                     }

                } else {
                    // Normal message analysis
                    // 1. Analyze message for struggle
                    console.log('🕵️ [CHAT_API_DEBUG] ------------------------------------------------');
                    console.log(`🕵️ [CHAT_API_DEBUG] Analysis Start for msg: "${message.substring(0, 50)}..."`);
                    
                    const analysis = await trackerService.analyzeMessage(message, courseId, unitName, approvedStruggleTopics);
                    console.log('🕵️ [CHAT_API_DEBUG] Raw Analysis Result:', JSON.stringify(analysis, null, 2));

                    if (analysis.isStruggling && analysis.isMapped) {
                        // 2. Update user state and persist to MongoDB for mapped topics only
                        const updateResult = await User.updateUserStruggleState(db, req.user.userId, analysis, courseId);
                        console.log('🕵️ [CHAT_API_DEBUG] User State Update Result:', JSON.stringify(updateResult, null, 2));

                        if (updateResult.success && !updateResult.skipped) {
                            struggleState = updateResult.state;
                            identifiedTopic = analysis.topic;

                            // 3. Check if Directive Mode should be active
                            if (struggleState && struggleState.isActive) {
                                directiveModeActive = true;
                                console.log(`🚨 [CHAT_API_DEBUG] Directive Mode ACTIVATED for topic: ${identifiedTopic}`);
                            } else {
                                 console.log(`🕵️ [CHAT_API_DEBUG] Struggle recorded but Directive Mode NOT active yet.`);
                            }
                        }
                    } else if (analysis.isStruggling && !analysis.isMapped) {
                        console.log(`🕵️ [CHAT_API_DEBUG] Struggle detected but topic unmapped; no struggle topic update applied.`);
                    } else {
                        console.log(`🕵️ [CHAT_API_DEBUG] No struggle detected for this message.`);
                    }
                }
            } catch (trackerError) {
                console.error('❌ [CHAT_API_DEBUG] Error in struggle tracking:', trackerError);
            }
        } else {
            console.warn('⚠️ [CHAT_API_DEBUG] Check skipped. User:', !!req.user, 'Tracker:', !!trackerService);
            if (!req.user) console.warn('⚠️ [CHAT_API_DEBUG] req.user is MISSING. Auth middleware might be failing.');
            if (!trackerService) console.warn('⚠️ [CHAT_API_DEBUG] trackerService is MISSING. LLM service might not be ready.');
        }


        // Fire-and-forget: parallel mental health detection LLM call
        // Only send trimmed context: most recent bot message + 2 most recent student messages
        const appLLMForMH = llmService;
        if (appLLMForMH && req.user) {
            (async () => {
                try {
                    const detectionPrompt = course.mentalHealthDetectionPrompt || prompts.DEFAULT_MENTAL_HEALTH_DETECTION_PROMPT;
                    const convMessages = (conversationContext && conversationContext.conversationMessages) || [];
                    // convMessages from frontend already includes the current message,
                    // so only append it if the history is empty (first message in chat)
                    const allMessages = convMessages.length > 0
                        ? convMessages
                        : [{ role: 'user', content: message }];

                    // Trim to last 2 student messages + last bot message
                    const recentStudentMsgs = allMessages.filter(m => m.role === 'user').slice(-2);
                    const recentBotMsg = [...allMessages].reverse().find(m => m.role === 'assistant');
                    const trimmedHistory = [];
                    if (recentBotMsg) trimmedHistory.push(recentBotMsg);
                    trimmedHistory.push(...recentStudentMsgs);

                    const result = await appLLMForMH.analyzeMentalHealth(trimmedHistory, detectionPrompt);

                    if (result.concernLevel !== 'no concern') {
                        await MentalHealthFlag.createMentalHealthFlag(db, {
                            studentId: req.user.userId,
                            studentName: req.user.displayName || req.user.username || 'Unknown',
                            courseId,
                            unitName,
                            message,
                            conversationContext: trimmedHistory,
                            concernLevel: result.concernLevel,
                            llmReason: result.reason
                        });
                    }
                } catch (err) {
                    console.error('Mental health detection error (non-blocking):', err);
                }
            })();
        }

        // Course is already loaded above for topic mapping; reuse it here for retrieval config.

        // Determine retrieval mode: Course override ? Default : False (default)
        const isAdditive = course.isAdditiveRetrieval !== undefined && course.isAdditiveRetrieval !== null
            ? !!course.isAdditiveRetrieval 
            : false;

        // Build lectureNames filter using published units only, ordered by lectures array
        const publishedLectures = (course.lectures || []).filter(l => l.isPublished).map(l => l.name);
        if (!publishedLectures.includes(unitName)) {
            return res.status(400).json({ success: false, message: 'Selected unit is not published or does not exist' });
        }

        let lectureNames = [unitName];
        if (isAdditive) {
            const order = (course.lectures || []).filter(l => l.isPublished).map(l => l.name);
            const idx = order.indexOf(unitName);
            lectureNames = idx >= 0 ? order.slice(0, idx + 1) : [unitName];
        }

        // Debug logging to verify retrieval mode and scope
        console.log(`🔎 [CHAT_RAG] RetrievalMode=${isAdditive ? 'additive' : 'single'} | Course=${courseId} | Unit=${unitName} | LectureNames=${JSON.stringify(lectureNames)}`);

        const ragSettings = CourseModel.resolveRagSettings(course);

        // Retrieve top chunks from Qdrant.
        // When the course de-prioritizes additional materials, search the main
        // materials (lecture notes, practice questions) first and only fall back
        // to additional materials if nothing was found there.
        let searchResults;
        if (course.additionalMaterialSecondarySearch === true) {
            searchResults = await qdrant.searchDocuments(message, { courseId, lectureNames, excludeAdditionalMaterials: true }, ragSettings.student.topK);
            if (!Array.isArray(searchResults) || searchResults.length === 0) {
                console.log('🔎 [CHAT_RAG] No chunks found in main materials; falling back to additional materials');
                searchResults = await qdrant.searchDocuments(message, { courseId, lectureNames, additionalMaterialsOnly: true }, ragSettings.student.topK);
            }
        } else {
            searchResults = await qdrant.searchDocuments(message, { courseId, lectureNames }, ragSettings.student.topK);
        }

        searchResults = normalizeQdrantSearchResults(searchResults);

        // Log summary of results by lecture to validate scope
        try {
            const lecturesHit = Array.from(new Set((searchResults || []).map(r => r.lectureName)));
            console.log(`📚 [CHAT_RAG] Retrieved ${searchResults.length} chunks from lectures: ${lecturesHit.join(', ')}`);
            // Group by document to see which files contributed
            const byDoc = {};
            for (const r of (searchResults || [])) {
                const docId = r.documentId || 'unknown-doc';
                if (!byDoc[docId]) {
                    byDoc[docId] = {
                        fileName: r.fileName || 'unknown-filename',
                        lectures: new Set(),
                        count: 0,
                        maxScore: 0
                    };
                }
                byDoc[docId].count += 1;
                byDoc[docId].lectures.add(r.lectureName);
                if (typeof r.score === 'number' && r.score > byDoc[docId].maxScore) {
                    byDoc[docId].maxScore = r.score;
                }
            }
            const docKeys = Object.keys(byDoc);
            console.log(`📄 [CHAT_RAG] Documents contributing (${docKeys.length}):`);
            for (const k of docKeys) {
                const info = byDoc[k];
                const lecturesList = Array.from(info.lectures).join(', ');
                const scoreStr = info.maxScore ? info.maxScore.toFixed(3) : 'n/a';
                console.log(`   - ${info.fileName} (id=${k}) | lectures=[${lecturesList}] | chunks=${info.count} | maxScore=${scoreStr}`);
            }
        } catch (_) {}

        // Build concise context window with citations
        const citations = searchResults.map(r => ({
            lectureName: r.lectureName,
            fileName: r.fileName,
            score: r.score
        }));
        const contextText = searchResults
            .map(r => `From ${r.lectureName} (${r.fileName}):\n${r.chunkText}`)
            .join('\n\n---\n\n');

        // Determine source attribution based on retrieved chunks
        console.log('🔍 [SOURCE_DEBUG] Retrieved chunks for source analysis:', searchResults.map(r => ({
            fileName: r.fileName,
            documentType: r.documentType,
            type: r.type,
            lectureName: r.lectureName
        })));

        let sourceAttribution;
        try {
            const sourceDownloadsEnabled = !!(course.quizSettings && course.quizSettings.allowSourceAttributionDownloads);
            sourceAttribution = await determineSourceAttribution(searchResults, unitName, sourceDownloadsEnabled);
            console.log('🔍 [SOURCE_DEBUG] Determined source attribution:', sourceAttribution);
        } catch (error) {
            console.error('🔍 [SOURCE_DEBUG] Error in source attribution:', error);
            sourceAttribution = {
                source: 'GPT',
                description: 'Generated by AI (error determining source)',
                unitName: null,
                documentType: null,
                downloadsEnabled: false,
                documents: []
            };
        }

        // Build the message to send to LLM
        let messageToSend;
        
        if (mode === 'protege') {
            messageToSend = `
CONTEXT (The correct answers):
${contextText}

INSTRUCTIONS:
Based on the Context above, act as the student described in the System Prompt.
The user just said: "${message}"
Do not explain the context to the user. Ask the user to explain it to you.`;
        } else if (req.body.isExplanationRequest) {
            // Explain mode
            messageToSend = `Use the provided course context to help explain the concept if needed.
\n\nCourse context:\n${contextText}\n\nConcept/Text to explain:\n"${message}"`;
        } else {
            // Default/Tutor mode
            messageToSend = `Use only the provided course context to answer. Cite which unit a fact came from.
\n\nCourse context:\n${contextText}\n\nStudent question: ${message}`;
        }

        // If we have conversation context (continuing a chat), use structured conversation approach
        if (conversationContext && conversationContext.conversationMessages) {
            console.log('🔄 [CHAT_CONTINUE] Using structured conversation context');

            // Build the conversation history as a single message
            let conversationHistory = '';
            conversationContext.conversationMessages.forEach(msg => {
                const speaker = msg.role === 'user' ? 'Student' : 'BiocBot';
                conversationHistory += `${speaker}: ${msg.content}\n\n`;
            });

            // Add the student's new message
            conversationHistory += `Student: ${message}`;

            // Create the full message with conversation context
            messageToSend = `Use only the provided course context to answer. Cite which unit a fact came from.

Course context:
${contextText}

Previous conversation:
${conversationHistory}`;
        }

        // Retrieve custom prompts from course object or use defaults
        let basePrompt = prompts.DEFAULT_PROMPTS.base;
        let protegePrompt = prompts.DEFAULT_PROMPTS.protege;
        let tutorPrompt = prompts.DEFAULT_PROMPTS.tutor;
        let explainPrompt = prompts.DEFAULT_PROMPTS.explain;
        let directivePrompt = prompts.DEFAULT_PROMPTS.directive;

        // Check if course has custom prompts
        if (course.prompts) {
            console.log('📝 [CHAT_API] Using course-specific prompts');
            if (course.prompts.base) basePrompt = course.prompts.base;
            if (course.prompts.protege) protegePrompt = course.prompts.protege;
            if (course.prompts.tutor) tutorPrompt = course.prompts.tutor;
            if (course.prompts.explain) explainPrompt = course.prompts.explain;
            if (course.prompts.directive) directivePrompt = course.prompts.directive;
        } else {
            console.log('[CHAT_API] Using default prompts');
        }

        // Apply Directive Mode adjustments if active
        // Apply Directive Mode adjustments if active
        if (directiveModeActive) {
            // Locked Trigger: Always prepend the topic announcement
            const lockedHeader = `\n\nCRITICAL INSTRUCTION: The student is struggling significantly with the topic "${identifiedTopic}".\nSwitch to DIRECTIVE MODE:\n`;
            
            // Configurable Strategy: Append the instructor's custom instructions
            // Append to TUTOR prompt only to avoid polluting Protege mode or Base
            tutorPrompt += lockedHeader + directivePrompt;
            
            console.log(' [CHAT_API] Appended Directive Mode instructions (Header + Strategy) to TUTOR prompt');
        }

        // Inject the unit's learning objectives directly into the prompt.
        // We read them deterministically per in-scope unit (single unit, or the
        // additive set when additive retrieval is on) so the objectives always
        // match the content the bot can actually retrieve — no keyword/vector
        // matching. They are appended to basePrompt so every mode (protege/"bot"
        // and tutor/explain/"student") sees them.
        try {
            const objectiveSections = [];
            for (const ln of lectureNames) {
                const objectives = await CourseModel.getLearningObjectives(db, courseId, ln);
                if (!objectives || objectives.length === 0) continue;

                // Shuffle so the model is not positionally biased toward the
                // first-listed objective; the instruction below also tells it to
                // treat them as an equally-weighted set.
                const shuffled = [...objectives].sort(() => Math.random() - 0.5);
                const list = shuffled.map((o, i) => `${i + 1}. ${o}`).join('\n');
                objectiveSections.push(`Learning objectives for ${ln}:\n${list}`);
            }

            if (objectiveSections.length > 0) {
                basePrompt += `\n\nLEARNING OBJECTIVES (the complete set of goals for the in-scope unit(s); treat every objective as equally important — do not fixate on or default to a single one, and cover the breadth of topics they span):\n\n${objectiveSections.join('\n\n')}`;
                console.log(`🎯 [CHAT_API] Injected learning objectives for unit(s): ${lectureNames.join(', ')}`);
            } else {
                console.log('🎯 [CHAT_API] No learning objectives found for in-scope unit(s)');
            }
        } catch (err) {
            console.error('🎯 [CHAT_API] Error injecting learning objectives:', err);
            // Non-fatal: continue without injected objectives.
        }

        // Check for summary attempt via LLM if requested
        let shouldAppendReprompt = false;
        if (req.body.checkSummaryAttempt) {
            try {
                console.log('🔍 [SUMMARY_CHECK] Analyzing student message for summary attempt...');
                const summaryCheckPrompt = `Analyze the following student message. Does it attempt to summarize, recap, or explain the previous conversation? Respond with only YES or NO. Message: "${message}"`;
                
                // Use a separate, cheap LLM call (low temp, system prompt irrelevant but using base for safety)
                const summaryCheckResponse = await llmService.sendMessage(summaryCheckPrompt, {
                    temperature: 0.1,
                    maxTokens: 10,
                    systemPrompt: "You are a classifier. Respond only with YES or NO."
                });

                const isSummary = summaryCheckResponse && summaryCheckResponse.content && summaryCheckResponse.content.trim().toUpperCase().includes('YES');
                console.log(`🔍 [SUMMARY_CHECK] Result: ${isSummary ? 'YES' : 'NO'} (Raw: ${summaryCheckResponse?.content})`);

                if (!isSummary) {
                    shouldAppendReprompt = true;
                    console.log('🔍 [SUMMARY_CHECK] Student did NOT summarize -> Appending re-prompt');
                } else {
                    console.log('🔍 [SUMMARY_CHECK] Student provided summary -> No re-prompt');
                }
            } catch (err) {
                console.error('❌ [SUMMARY_CHECK] Error during check:', err);
                // Fail safe: don't annoy the user if check fails. Or default to true? 
                // Let's default to false (no re-prompt) to be safe.
            }
        }

        // In the future, we can implement conversation persistence
        let response = await llmService.sendMessage(
            messageToSend,
            {
            // Adjust response based on student mode
            temperature: mode === 'protege' ? 0.5 : 0.5,
            maxTokens: mode === 'protege' ? 32768 : 32768,
            systemPrompt: basePrompt +
                (req.body.isExplanationRequest ? explainPrompt : 
                (mode === 'protege' ? protegePrompt : tutorPrompt))
        });

        let fullContent = response && response.content ? response.content : '';

        // Detect truncation and auto-continue up to N times
        function extractFinishReason(resp) {
            try {
                return (resp && (resp.finishReason || resp.finish_reason || (resp.usage && resp.usage.finish_reason) || resp.stopReason || resp.stop_reason)) || '';
            } catch (e) { return ''; }
        }
        function isLikelyTruncated(resp, content) {
            const fr = (extractFinishReason(resp) + '').toLowerCase();
            if (fr.includes('length') || fr.includes('token')) return true;
            if (!content) return false;
            const tail = content.trim().slice(-60);
            // Check for clean sentence endings: punctuation, parenthetical unit refs, or emoji
            const endsClean = /([\.\!\?\)\u2026]|\(Unit\s+[^)]+\))\s*$/i.test(tail);
            // Only consider truncated if very long AND no clean ending AND finish reason wasn't 'stop'
            if (fr === 'stop' || fr === 'end_turn') return false;
            return !endsClean && content.length > 800;
        }

        const MAX_CONTINUATIONS = 2;
        let cont = 0;
        while (cont < MAX_CONTINUATIONS && isLikelyTruncated(response, fullContent)) {
            cont += 1;
            console.log(`⏩ [CHAT_CONTINUE] Requesting continuation ${cont}; current length=${fullContent.length}`);
            const tailSnippet = fullContent.slice(-200);
            const contPrompt = `Continue the previous answer. Do not repeat earlier content. Pick up seamlessly from here: "${tailSnippet}"`;
            const contResp = await llmService.sendMessage(contPrompt, {
                temperature: mode === 'protege' ? 0.8 : 0.6,
                maxTokens: mode === 'protege' ? 32768 : 32768,
                systemPrompt: basePrompt +
                    (mode === 'protege' ? protegePrompt : tutorPrompt)
            });
            const chunk = contResp && contResp.content ? contResp.content : '';
            console.log(`📎 [CHAT_CONTINUE] Received chunk ${cont} length=${chunk.length}`);
            if (chunk) {
                fullContent += (fullContent.endsWith('\n') ? '' : '\n') + chunk;
            }
            response = contResp;
        }

        // Append the re-prompt if the summary check determined it was needed
        if (shouldAppendReprompt) {
            fullContent += '\n\n----------------\nHey, I know you asked another question, would you like to summarize our chat again?';
        }

        // Format response for frontend
        const chatResponse = {
            success: true,
            messageId: generateChatMessageId(),
            message: fullContent,
            model: response.model,
            usage: response.usage,
            timestamp: new Date().toISOString(),
            mode: mode || 'default',
            citations,
            sourceAttribution,
            debug: {
                searchResultsCount: searchResults.length,
                avgScore: searchResults.length > 0 ? searchResults.reduce((sum, result) => sum + (result.score || 0), 0) / searchResults.length : 0,
                maxScore: searchResults.length > 0 ? Math.max(...searchResults.map(result => result.score || 0)) : 0,
                documentTypes: searchResults.map(r => ({ fileName: r.fileName, documentType: r.documentType, type: r.type, score: r.score }))
            },
            retrieval: {
                mode: isAdditive ? 'additive' : 'single',
                lectureNames
            },
            struggleState: struggleState,
            struggleDebug: {
                userExists: !!req.user,
                userId: req.user ? req.user.userId : null,
                trackerInitialized: !!trackerService,
                directiveModeActive: directiveModeActive,
                identifiedTopic: identifiedTopic
            }
        };

        console.log(`✅ Chat response sent successfully`);

        res.json(chatResponse);

    } catch (error) {
        if (sendLlmKeyError(res, error)) return;
        console.error('❌ Error in chat endpoint:', error);

        // Provide user-friendly error messages
        let errorMessage = 'Sorry, I encountered an error processing your message.';
        let statusCode = 500;

        if (error.message.includes('OLLAMA_ENDPOINT')) {
            errorMessage = 'Ollama service is not available. Please check if Ollama is running.';
            statusCode = 503;
        } else if (error.message.includes('API key')) {
            errorMessage = 'Authentication error. Please check your API configuration.';
            statusCode = 401;
        } else if (error.message.includes('endpoint')) {
            errorMessage = 'Service endpoint is not reachable. Please check your configuration.';
            statusCode = 503;
        }

        res.status(statusCode).json({
            success: false,
            message: errorMessage,
            error: process.env.NODE_ENV === 'development' ? error.message : undefined,
            timestamp: new Date().toISOString()
        });
    }
});


/**
 * GET /api/chat/status
 * Get the current status of the LLM service
 */
router.get('/status', async (req, res) => {
    try {
        let llmService = req.app.locals.llm;
        const courseId = (req.query && req.query.courseId) || (req.body && req.body.courseId);
        if (!llmService && courseId) {
            const ai = await resolveCourseAi(req, res, courseId);
            if (!ai) return;
            llmService = ai.llm;
        }

        if (!llmService) {
            return res.status(503).json({
                success: false,
                message: 'LLM service is not initialized'
            });
        }

        const status = llmService.getStatus();

        res.json({
            success: true,
            data: status
        });

    } catch (error) {
        console.error('❌ Error getting chat status:', error);

        res.status(500).json({
            success: false,
            message: 'Failed to get chat status',
            error: process.env.NODE_ENV === 'development' ? error.message : undefined
        });
    }
});



/**
 * POST /api/chat/test
 * Test the LLM connection
 */
router.post('/test', async (req, res) => {
    try {
        console.log('🧪 Testing LLM connection...');

        let llmService = req.app.locals.llm;
        const courseId = req.body && req.body.courseId;
        if (!llmService && courseId) {
            const ai = await resolveCourseAi(req, res, courseId);
            if (!ai) return;
            llmService = ai.llm;
        }

        if (!llmService) {
            return res.status(503).json({
                success: false,
                message: 'LLM service is not initialized'
            });
        }

        const isConnected = await llmService.testConnection();

        if (isConnected) {
            res.json({
                success: true,
                message: 'LLM connection test successful',
                provider: llmService.getProviderName(),
                timestamp: new Date().toISOString()
            });
        } else {
            res.status(503).json({
                success: false,
                message: 'LLM connection test failed',
                provider: llmService.getProviderName(),
                timestamp: new Date().toISOString()
            });
        }

    } catch (error) {
        console.error('❌ Error testing LLM connection:', error);

        res.status(500).json({
            success: false,
            message: 'Failed to test LLM connection',
            error: process.env.NODE_ENV === 'development' ? error.message : undefined,
            timestamp: new Date().toISOString()
        });
    }
});

/**
 * GET /api/chat/models
 * Get available models from the current provider
 */
router.get('/models', async (req, res) => {
    try {
        const llmService = req.app.locals.llm;

        if (!llmService) {
            return res.status(503).json({
                success: false,
                message: 'LLM service is not initialized'
            });
        }

        const models = await llmService.getAvailableModels();

        res.json({
            success: true,
            data: {
                models: models,
                provider: llmService.getProviderName(),
                timestamp: new Date().toISOString()
            }
        });

    } catch (error) {
        console.error('❌ Error getting available models:', error);

        res.status(500).json({
            success: false,
            message: 'Failed to get available models',
            error: process.env.NODE_ENV === 'development' ? error.message : undefined
        });
    }
});

/**
 * POST /api/chat/save
 * Save a chat session to the database for instructor access
 */
router.post('/save', async (req, res) => {
    try {
        const {
            sessionId,
            courseId,
            studentId,
            studentName,
            unitName,
            title,
            messageCount,
            duration,
            savedAt,
            chatData
        } = req.body;

        // Validate required fields
        if (!sessionId || !courseId || !studentId || !studentName) {
            return res.status(400).json({
                success: false,
                message: 'Missing required fields: sessionId, courseId, studentId, studentName'
            });
        }

        if (req.user?.role === 'student' && req.user.userId !== studentId) {
            return res.status(403).json({
                success: false,
                message: 'You can only save chat sessions for your own account'
            });
        }

        // Get database instance from app.locals
        const db = req.app.locals.db;
        if (!db) {
            return res.status(503).json({
                success: false,
                message: 'Database connection not available'
            });
        }

        // Save chat session to database
        const chatSessionsCollection = db.collection('chat_sessions');

        const sessionData = {
            sessionId,
            courseId,
            studentId,
            studentName,
            unitName: unitName || 'Unknown Unit',
            title: title || `Chat Session ${new Date().toLocaleDateString()}`,
            messageCount: messageCount || 0,
            duration: duration || 'Unknown',
            savedAt: savedAt || new Date().toISOString(),
            chatData: chatData || {},
            isDeleted: false, // Soft deletion flag
            createdAt: new Date()
        };

        // Insert or update the session
        await chatSessionsCollection.replaceOne(
            { sessionId: sessionId },
            sessionData,
            { upsert: true }
        );

        console.log(`Chat session saved: ${sessionId} for student ${studentName} in course ${courseId}`);

        res.json({
            success: true,
            message: 'Chat session saved successfully',
            data: {
                sessionId: sessionId,
                courseId: courseId,
                studentId: studentId
            }
        });

    } catch (error) {
        console.error('Error saving chat session:', error);
        res.status(500).json({
            success: false,
            message: 'Internal server error while saving chat session'
        });
    }
});

// ─── Practice Question: generate a new question from unit assessment questions ───
// In-memory store for generated practice questions (keyed by a temp ID)
// so we never send the correct answer to the client
const practiceQuestionStore = new Map();

router.post('/practice-question', async (req, res) => {
    try {
        const { courseId, unitName, topic } = req.body;

        if (!courseId || !unitName) {
            return res.status(400).json({ success: false, message: 'courseId and unitName are required.' });
        }

        const db = req.app.locals.db;

        // Pull assessment questions for this unit
        const allQuestions = await CourseModel.getAssessmentQuestions(db, courseId, unitName);

        if (!allQuestions || allQuestions.length === 0) {
            return res.json({
                success: true,
                noQuestions: true,
                message: 'There are no questions to practice right now.'
            });
        }

        // Pick up to 6 random questions as seed material
        const shuffled = [...allQuestions].sort(() => 0.5 - Math.random());
        const seedQuestions = shuffled.slice(0, 6);

        // Build a prompt for the LLM to generate a NEW question
        const seedText = seedQuestions.map((q, i) => {
            let entry = `${i + 1}. [${q.questionType}] ${q.question}`;
            if (q.options && typeof q.options === 'object') {
                entry += '\n   Options: ' + Object.entries(q.options).map(([k, v]) => `${k}. ${v}`).join(' | ');
            }
            entry += `\n   Answer: ${q.correctAnswer}`;
            if (q.explanation) entry += `\n   Explanation: ${q.explanation}`;
            return entry;
        }).join('\n\n');

        const generationPrompt = prompts.buildPracticeQuestionPrompt(seedText, topic);

        const ai = await resolveCourseAi(req, res, courseId);
        if (!ai) return;
        const llmService = ai.llm;

        const llmResponse = await llmService.sendMessage(generationPrompt, {
            temperature: 0.7,
            response_format: { type: "json_object" }
        });

        // Parse the generated question
        let generated;
        try {
            const jsonStart = llmResponse.content.indexOf('{');
            const jsonEnd = llmResponse.content.lastIndexOf('}') + 1;
            if (jsonStart !== -1 && jsonEnd !== 0) {
                generated = JSON.parse(llmResponse.content.substring(jsonStart, jsonEnd));
            } else {
                throw new Error('No JSON found in LLM response');
            }
        } catch (parseErr) {
            console.error('❌ Failed to parse practice question JSON:', parseErr);
            return res.status(500).json({ success: false, message: 'Failed to generate a practice question. Please try again.' });
        }

        // Validate required fields
        if (!generated.questionType || !generated.question || !generated.correctAnswer) {
            return res.status(500).json({ success: false, message: 'Generated question was incomplete. Please try again.' });
        }

        // Store correct answer server-side, keyed by a temp ID
        const practiceId = createId('pq');
        practiceQuestionStore.set(practiceId, {
            courseId,
            correctAnswer: generated.correctAnswer,
            explanation: generated.explanation || '',
            question: generated.question,
            questionType: generated.questionType,
            createdAt: Date.now()
        });

        // Send to client WITHOUT correctAnswer
        const clientQuestion = {
            practiceId,
            questionType: generated.questionType,
            question: generated.question
        };
        if (generated.questionType === 'multiple-choice' && generated.options) {
            clientQuestion.options = generated.options;
        }

        res.json({ success: true, data: clientQuestion });

    } catch (error) {
        if (sendLlmKeyError(res, error)) return;
        console.error('❌ Error generating practice question:', error);
        res.status(500).json({ success: false, message: 'Failed to generate practice question.' });
    }
});

// ─── Check Practice Answer ───
router.post('/check-practice-answer', async (req, res) => {
    try {
        const { practiceId, studentAnswer, studentName } = req.body;

        if (!practiceId || !studentAnswer) {
            return res.status(400).json({ success: false, message: 'practiceId and studentAnswer are required.' });
        }

        const stored = practiceQuestionStore.get(practiceId);
        if (!stored) {
            return res.status(404).json({ success: false, message: 'Practice question not found or expired. Please generate a new one.' });
        }

        const { courseId, correctAnswer, explanation, question, questionType } = stored;

        if (questionType === 'short-answer') {
            // Use LLM evaluation for short-answer
            const ai = await resolveCourseAi(req, res, courseId);
            if (!ai) return;
            const llmService = ai.llm;

            const result = await llmService.evaluateStudentAnswer(
                question,
                studentAnswer,
                correctAnswer,
                questionType,
                studentName || 'Student'
            );

            return res.json({
                success: true,
                data: {
                    correct: result.correct,
                    feedback: result.feedback,
                    correctAnswer: correctAnswer,
                    explanation: explanation
                }
            });
        } else {
            const evaluated = evaluateObjectiveAnswer({ correctAnswer }, studentAnswer);

            return res.json({
                success: true,
                data: {
                    ...evaluated,
                    feedback: evaluated.feedback + (explanation ? ` ${explanation}` : '')
                }
            });
        }

    } catch (error) {
        if (sendLlmKeyError(res, error)) return;
        console.error('❌ Error checking practice answer:', error);
        res.status(500).json({ success: false, message: 'Failed to check answer.' });
    }
});

module.exports = router;
