/**
 * Chat API Routes
 * Handles chat functionality with real LLM integration
 * Replaces mock responses with actual AI-powered responses
 */

const express = require('express');
const path = require('path');
const router = express.Router();
const LLMService = require('../services/llm');
const QdrantService = require('../services/qdrantService');
const prompts = require('../services/prompts');
const CourseModel = require('../models/Course');
const DocumentModel = require('../models/Document');
const BadWordsFilter = require('bad-words');
const profanityFilter = new BadWordsFilter();
const TrackerService = require('../services/tracker');
const User = require('../models/User');
const MentalHealthFlag = require('../models/MentalHealthFlag');

// Initialize services
// Initialize services lazily
let localTrackerService;

/**
 * Determine source attribution based on retrieved chunks
 * @param {Array} searchResults - Array of search results from Qdrant
 * @param {string} unitName - Current unit name
 * @param {boolean} sourceDownloadsEnabled - Whether source document downloads are enabled for the course
 * @returns {Promise<Object>} Source attribution information
 */
/**
 * Determine source attribution based on retrieved chunks
 * @param {Array} searchResults - Array of search results from Qdrant
 * @param {string} unitName - Current unit name
 * @param {boolean} sourceDownloadsEnabled - Whether source document downloads are enabled for the course
 * @returns {Promise<Object>} Source attribution information
 */
async function determineSourceAttribution(searchResults, unitName, sourceDownloadsEnabled = false) {
    try {
        // If no search results, content is from GPT
        if (!searchResults || searchResults.length === 0) {
            return {
                source: 'GPT',
                description: 'Generated by AI (no relevant course materials found)',
                unitName: null,
                documentType: null,
                downloadsEnabled: false,
                documents: []
            };
        }

        // Check if search results are relevant enough (low scores indicate poor matches)
        const scores = searchResults.map(result => (result.score || 0));
        const maxScore = Math.max(...scores);
        const top3Scores = [...scores].sort((a, b) => b - a).slice(0, 3);
        const avgTop3Score = top3Scores.length > 0
            ? top3Scores.reduce((sum, score) => sum + score, 0) / top3Scores.length
            : 0;

        console.log('🔍 [SOURCE_DEBUG] Search relevance - avgTop3Score:', avgTop3Score, 'maxScore:', maxScore);

        // Treat as GPT only when both max and top-hit average are weak.
        if (avgTop3Score < 0.10 && maxScore < 0.18) {
            console.log('🔍 [SOURCE_DEBUG] Low relevance scores - treating as GPT');
            return {
                source: 'GPT',
                description: 'Generated by AI (no relevant course materials found)',
                unitName: null,
                documentType: null,
                downloadsEnabled: false,
                documents: []
            };
        }

        // Filter for meaningful chunks
        const relevantChunks = searchResults.filter(result => (result.score || 0) > 0.10);

        if (relevantChunks.length === 0) {
             return {
                source: 'GPT',
                description: 'Generated by AI (no relevant course materials found)',
                unitName: null,
                documentType: null,
                downloadsEnabled: false,
                documents: []
            };
        }

        // Collect unique sources
        const sources = new Set();
        const sourceDocuments = new Map();
        
        relevantChunks.forEach(chunk => {
            const docType = chunk.type || chunk.documentType || 'unknown';
            const sourceUnit = chunk.lectureName || unitName;
            const score = typeof chunk.score === 'number' ? chunk.score : 0;
            
            let readableType = 'Material';
            switch (docType) {
                case 'lecture_notes': readableType = 'Lecture Notes'; break;
                case 'practice_q_tutorials':
                case 'practice-quiz':
                    readableType = 'Practice Questions';
                    break;
                case 'additional': readableType = 'Additional Materials'; break;
                default: readableType = 'Course Material';
            }

            sources.add(`${readableType} (${sourceUnit})`);

            const rawDocumentId = typeof chunk.documentId === 'string' ? chunk.documentId.trim() : '';
            const documentId = rawDocumentId || null;
            const fileName = (typeof chunk.fileName === 'string' && chunk.fileName.trim())
                ? chunk.fileName.trim()
                : readableType;
            const dedupeKey = documentId || `${fileName}::${sourceUnit}`;
            const existing = sourceDocuments.get(dedupeKey);

            if (!existing) {
                sourceDocuments.set(dedupeKey, {
                    documentId,
                    fileName,
                    lectureName: sourceUnit || unitName || null,
                    maxScore: score
                });
            } else if (score > existing.maxScore) {
                existing.maxScore = score;
            }
        });

        // Debug: Log details about practice quiz chunks specifically
        const practiceQuizChunks = searchResults.filter(r => r.type === 'practice_q_tutorials' || r.documentType === 'practice-quiz');
        if (practiceQuizChunks.length > 0) {
            console.log('🔍 [SOURCE_DEBUG] Practice quiz chunks found:', practiceQuizChunks.length);
        }

        const sortedSourceDocs = Array.from(sourceDocuments.values())
            .sort((a, b) => b.maxScore - a.maxScore);
        const sourceDescription = sortedSourceDocs.length > 0
            ? sortedSourceDocs
                .map(doc => `${doc.fileName}${doc.lectureName ? ` (${doc.lectureName})` : ''}`)
                .join(', ')
            : Array.from(sources).join(', ');
        console.log('🔍 [SOURCE_DEBUG] Final Source Description:', sourceDescription);

        const downloadableDocuments = sortedSourceDocs
            .filter(doc => !!doc.documentId)
            .map(doc => ({
                documentId: doc.documentId,
                fileName: doc.fileName,
                lectureName: doc.lectureName
            }));

        return {
            source: 'multiple',
            description: `From: ${sourceDescription || 'Course Material'}`,
            unitName: unitName,
            documentType: 'multiple',
            downloadsEnabled: !!sourceDownloadsEnabled,
            documents: sourceDownloadsEnabled ? downloadableDocuments : []
        };

    } catch (error) {
        console.error('Error determining source attribution:', error);
        return {
            source: 'GPT',
            description: 'Generated by AI (error determining source)',
            unitName: null,
            documentType: null,
            downloadsEnabled: false,
            documents: []
        };
    }
}

function inferExtensionFromMimeType(mimeType) {
    switch ((mimeType || '').toLowerCase()) {
        case 'application/pdf':
            return '.pdf';
        case 'text/markdown':
            return '.md';
        case 'application/msword':
            return '.doc';
        case 'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
            return '.docx';
        case 'application/rtf':
            return '.rtf';
        case 'text/plain':
            return '.txt';
        default:
            return '';
    }
}

function resolveDownloadFilename(document) {
    const fallbackName = `source-${document.documentId || Date.now()}`;
    const rawOriginal = (document.originalName || '').trim();
    const rawFile = (document.filename || '').trim();
    const preferredName = rawOriginal || rawFile || fallbackName;
    let safeName = path.basename(preferredName).replace(/[\r\n]/g, '');

    if (!path.extname(safeName)) {
        if (rawFile && path.extname(rawFile)) {
            safeName = path.basename(rawFile).replace(/[\r\n]/g, '');
        } else {
            safeName += inferExtensionFromMimeType(document.mimeType);
        }
    }

    return safeName || `${fallbackName}.txt`;
}

function setAttachmentHeaders(res, filename) {
    const encodedName = encodeURIComponent(filename);
    const asciiFallback = filename.replace(/[^\x20-\x7E]/g, '_').replace(/"/g, '');
    res.setHeader(
        'Content-Disposition',
        `attachment; filename="${asciiFallback}"; filename*=UTF-8''${encodedName}`
    );
}

/**
 * Analyze chunk sources to determine document types
 * @param {Array} searchResults - Array of search results
 * @returns {Object} Analysis of chunk sources
 */
function analyzeChunkSources(searchResults) {
    const analysis = {
        hasLectureNotes: false,
        hasAdditionalMaterials: false,
        hasPracticeQuiz: false,
        hasUnknownType: false
    };

    for (const result of searchResults) {
        const docType = result.type || result.documentType || 'unknown';
        console.log('🔍 [SOURCE_DEBUG] Analyzing chunk with docType:', docType, 'fileName:', result.fileName);

        switch (docType) {
            case 'lecture_notes':
                analysis.hasLectureNotes = true;
                break;
            case 'additional':
                analysis.hasAdditionalMaterials = true;
                break;
            case 'practice_q_tutorials':
                analysis.hasPracticeQuiz = true;
                break;
            case 'unknown':
                analysis.hasUnknownType = true;
                // Try to infer type from filename for legacy documents
                const fileName = (result.fileName || '').toLowerCase();
                console.log('🔍 [SOURCE_DEBUG] Inferring type from filename:', fileName);

                // Be more specific about lecture notes inference
                if (fileName.includes('lecture') && (fileName.includes('notes') || fileName.includes('note'))) {
                    analysis.hasLectureNotes = true;
                } else if (fileName.includes('practice') || fileName.includes('quiz') || fileName.includes('tutorial')) {
                    analysis.hasPracticeQuiz = true;
                } else {
                    // Default to additional materials for unknown types
                    analysis.hasAdditionalMaterials = true;
                }
                break;
        }
    }

    return analysis;
}

/**
 * Check if retrieved chunks match learning objectives content
 * @param {Array} searchResults - Array of search results
 * @param {string} courseId - Course ID
 * @param {string} unitName - Unit name
 * @param {Object} db - Database instance
 * @returns {Promise<boolean>} True if chunks match learning objectives
 */
async function checkLearningObjectivesMatch(searchResults, courseId, unitName, db) {
    try {
        // Get learning objectives for the unit
        const learningObjectives = await CourseModel.getLearningObjectives(db, courseId, unitName);

        if (!learningObjectives || learningObjectives.length === 0) {
            return false;
        }

        // Check if any chunk text contains learning objective keywords
        const objectiveKeywords = learningObjectives.flatMap(obj =>
            obj.toLowerCase().split(/\s+/).filter(word => word.length > 3)
        );

        for (const result of searchResults) {
            const chunkText = result.chunkText.toLowerCase();
            const matches = objectiveKeywords.filter(keyword =>
                chunkText.includes(keyword)
            );

            // If chunk matches multiple learning objective keywords, likely from objectives
            if (matches.length >= 2) {
                return true;
            }
        }

        return false;
    } catch (error) {
        console.error('Error checking learning objectives match:', error);
        return false;
    }
}

// Middleware to parse JSON bodies
router.use(express.json());

/**
 * GET /api/chat/source-documents/:documentId/download
 * Download a source-attributed document when enabled for the course
 */
router.get('/source-documents/:documentId/download', async (req, res) => {
    try {
        const { documentId } = req.params;
        const { courseId } = req.query;

        if (!documentId || !courseId) {
            return res.status(400).json({ success: false, message: 'Missing documentId or courseId' });
        }

        const user = req.user;
        if (!user) {
            return res.status(401).json({ success: false, message: 'Authentication required' });
        }

        const db = req.app.locals.db;
        if (!db) {
            return res.status(503).json({ success: false, message: 'Database connection not available' });
        }

        const course = await db.collection('courses').findOne(
            { courseId },
            { projection: { courseId: 1, quizSettings: 1 } }
        );
        if (!course) {
            return res.status(404).json({ success: false, message: 'Course not found' });
        }

        const downloadsEnabled = !!(course.quizSettings && course.quizSettings.allowSourceAttributionDownloads);
        if (!downloadsEnabled) {
            return res.status(403).json({ success: false, message: 'Source attribution downloads are not enabled for this course' });
        }

        let hasAccess = false;
        if (user.role === 'student') {
            const enrollment = await CourseModel.getStudentEnrollment(db, courseId, user.userId);
            hasAccess = !!(enrollment.success && enrollment.enrolled);
        } else if (user.role === 'instructor' || user.role === 'ta') {
            hasAccess = await CourseModel.userHasCourseAccess(db, courseId, user.userId, user.role);
        }

        if (!hasAccess) {
            return res.status(403).json({ success: false, message: 'Access denied for this course' });
        }

        const document = await DocumentModel.getDocumentById(db, documentId);
        if (!document || document.courseId !== courseId) {
            return res.status(404).json({ success: false, message: 'Document not found' });
        }

        const downloadFilename = resolveDownloadFilename(document);
        setAttachmentHeaders(res, downloadFilename);

        if (document.contentType === 'file' && document.fileData) {
            const payload = Buffer.isBuffer(document.fileData)
                ? document.fileData
                : (document.fileData.buffer ? Buffer.from(document.fileData.buffer) : null);

            if (!payload) {
                return res.status(500).json({ success: false, message: 'Stored file data is invalid' });
            }

            res.setHeader('Content-Type', document.mimeType || 'application/octet-stream');
            return res.send(payload);
        }

        const textContent = typeof document.content === 'string' ? document.content : '';
        res.setHeader('Content-Type', `${document.mimeType || 'text/plain'}; charset=utf-8`);
        return res.send(textContent);
    } catch (error) {
        console.error('Error downloading source-attributed document:', error);
        res.status(500).json({ success: false, message: 'Failed to download source document' });
    }
});

/**
 * POST /api/chat
 * Send a message to the LLM and get a response
 */
router.post('/', async (req, res) => {
    try {
        console.log('🔥 [CHAT_ROUTE_HIT] Processing POST /api/chat');
        console.log('💬 [CHAT_API] New chat request received');
        console.log('💬 [CHAT_API] Message:', req.body.message?.substring(0, 50) + '...');
        console.log('💬 [CHAT_API] Has conversationContext:', !!req.body.conversationContext);
        console.log('🔐 [CHAT_API] Auth check - Cookie present:', !!req.headers.cookie);
        console.log('🔐 [CHAT_API] Auth check - User present:', !!req.user);

        const llmService = req.app.locals.llm;

        // Check if LLM service is initialized
        if (!llmService) {
            return res.status(503).json({
                success: false,
                message: 'LLM service is not yet initialized. Please try again in a moment.'
            });
        }

        const { message, conversationId, mode, unitName, courseId, conversationContext } = req.body;

        // Get DB connection early
        const db = req.app.locals.db;
        if (!db) {
            return res.status(503).json({ success: false, message: 'Database connection not available' });
        }


        // Validate required fields
        if (!message || typeof message !== 'string') {
            return res.status(400).json({
                success: false,
                message: 'Message is required and must be a string'
            });
        }

        console.log(`💬 Chat request received: "${message.substring(0, 50)}..."`);
        console.log(`🎯 Mode: ${mode || 'default'}`);

        // Require courseId and unitName per requirements
        if (!courseId || !unitName) {
            return res.status(400).json({
                success: false,
                message: 'courseId and unitName are required to start chat'
            });
        }

        // Profanity filter: intercept before any RAG/GPT work to save tokens
        // If the cleaned text differs from the original, return a warning response
        // Skip for explanation requests (system generated from valid bot content)
        if (!req.body.isExplanationRequest) {
            const cleanedMessage = profanityFilter.clean(message);

            if (cleanedMessage !== message) {
            const warningText = 'please watch the language, this is a tool and this data will be used for internal and data analysis';
            console.log('⚠️ [CHAT_API] Profanity detected. Returning warning without querying LLM.');
            return res.json({
                success: true,
                message: warningText,
                model: 'system',
                usage: { tokens: 0 },
                timestamp: new Date().toISOString(),
                mode: mode || 'default',
                citations: [],
                sourceAttribution: {
                    source: 'system',
                    description: 'Profanity filtered warning',
                    unitName: null,
                    documentType: null,
                    downloadsEnabled: false,
                    documents: []
                },
                debug: {
                    profanityFiltered: true
                },
                retrieval: {
                    mode: 'n/a',
                    lectureNames: []
                }

            });
        }
    }
        
        
        // Mental health detection is handled by the parallel LLM detection (fire-and-forget)
        // The chat bot's mode prompts include SAFETY PROTOCOL to provide the wellness link directly

        // Load course early (used by both struggle mapping and retrieval config)
        const coursesCol = db.collection('courses');
        const course = await coursesCol.findOne({ courseId });
        if (!course) {
            return res.status(404).json({ success: false, message: 'Course not found' });
        }

        const approvedStruggleTopics = CourseModel.normalizeTopicList(course.approvedStruggleTopics || []);
        console.log(`🧭 [CHAT_TOPIC_MAP] Approved topics loaded: ${approvedStruggleTopics.length}`);

        // STRUGGLE DETECTION & TRACKING
        let struggleState = null;
        let directiveModeActive = false;
        let identifiedTopic = null;

        // Initialize TrackerService if needed
        const appLLM = req.app.locals.llm;
        if (appLLM && !localTrackerService) {
            localTrackerService = new TrackerService(appLLM);
            console.log('✅ [CHAT_API_DEBUG] Local TrackerService initialized from app.locals.llm');
        }

        console.log(`🕵️ [CHAT_API_DEBUG] User Context: ID=${req.user ? req.user.userId : 'MISSING'}, Tracker=${!!localTrackerService}`);

        if (req.user && localTrackerService) {
            try {
                // Check if this is an explanation request with a known topic
                // If so, we can skip analysis and directly increment struggle for that topic
                if (req.body.isExplanationRequest && req.body.topic) {
                     const explanationTopic = String(req.body.topic || '').trim();
                     const matchedApprovedTopic = approvedStruggleTopics.find(
                        topic => topic.toLowerCase() === explanationTopic.toLowerCase()
                     );

                     if (!matchedApprovedTopic) {
                        console.log(`🕵️ [CHAT_API_DEBUG] Explanation topic "${explanationTopic}" is not approved; skipping struggle update.`);
                     } else {
                        console.log(`🕵️ [CHAT_API_DEBUG] Explanation Request for approved topic: "${matchedApprovedTopic}" - Incrementing Struggle Count`);

                        const updateResult = await User.updateUserStruggleState(db, req.user.userId, {
                            topic: matchedApprovedTopic,
                            isStruggling: true,
                            reason: 'User requested explanation'
                        }, courseId);

                        console.log('🕵️ [CHAT_API_DEBUG] Struggle Update (Explain) Result:', JSON.stringify(updateResult, null, 2));

                        if (updateResult.success && !updateResult.skipped) {
                            struggleState = updateResult.state; // topic specific state
                            identifiedTopic = matchedApprovedTopic;

                            // We also need the full state to determine if ANY directive mode is active
                            // But updateUserStruggleState returns { success, state, allTopics }
                            // Let's verify if *this* topic triggered directive mode
                            if (struggleState && struggleState.isActive) {
                                directiveModeActive = true;
                                console.log(`🚨 [CHAT_API_DEBUG] Directive Mode ACTIVATED via Explain for topic: ${identifiedTopic}`);
                            }
                        }
                     }

                } else {
                    // Normal message analysis
                    // 1. Analyze message for struggle
                    console.log('🕵️ [CHAT_API_DEBUG] ------------------------------------------------');
                    console.log(`🕵️ [CHAT_API_DEBUG] Analysis Start for msg: "${message.substring(0, 50)}..."`);
                    
                    const analysis = await localTrackerService.analyzeMessage(message, courseId, unitName, approvedStruggleTopics);
                    console.log('🕵️ [CHAT_API_DEBUG] Raw Analysis Result:', JSON.stringify(analysis, null, 2));

                    if (analysis.isStruggling && analysis.isMapped) {
                        // 2. Update user state and persist to MongoDB for mapped topics only
                        const updateResult = await User.updateUserStruggleState(db, req.user.userId, analysis, courseId);
                        console.log('🕵️ [CHAT_API_DEBUG] User State Update Result:', JSON.stringify(updateResult, null, 2));

                        if (updateResult.success && !updateResult.skipped) {
                            struggleState = updateResult.state;
                            identifiedTopic = analysis.topic;

                            // 3. Check if Directive Mode should be active
                            if (struggleState && struggleState.isActive) {
                                directiveModeActive = true;
                                console.log(`🚨 [CHAT_API_DEBUG] Directive Mode ACTIVATED for topic: ${identifiedTopic}`);
                            } else {
                                 console.log(`🕵️ [CHAT_API_DEBUG] Struggle recorded but Directive Mode NOT active yet.`);
                            }
                        }
                    } else if (analysis.isStruggling && !analysis.isMapped) {
                        console.log(`🕵️ [CHAT_API_DEBUG] Struggle detected but topic unmapped; no struggle topic update applied.`);
                    } else {
                        console.log(`🕵️ [CHAT_API_DEBUG] No struggle detected for this message.`);
                    }
                }
            } catch (trackerError) {
                console.error('❌ [CHAT_API_DEBUG] Error in struggle tracking:', trackerError);
            }
        } else {
            console.warn('⚠️ [CHAT_API_DEBUG] Check skipped. User:', !!req.user, 'Tracker:', !!localTrackerService);
            if (!req.user) console.warn('⚠️ [CHAT_API_DEBUG] req.user is MISSING. Auth middleware might be failing.');
            if (!localTrackerService) console.warn('⚠️ [CHAT_API_DEBUG] localTrackerService is MISSING. LLM service might not be ready.');
        }


        // Fire-and-forget: parallel mental health detection LLM call
        // Only send trimmed context: most recent bot message + 2 most recent student messages
        const appLLMForMH = req.app.locals.llm;
        if (appLLMForMH && req.user) {
            (async () => {
                try {
                    const detectionPrompt = course.mentalHealthDetectionPrompt || prompts.DEFAULT_MENTAL_HEALTH_DETECTION_PROMPT;
                    const convMessages = (conversationContext && conversationContext.conversationMessages) || [];
                    // convMessages from frontend already includes the current message,
                    // so only append it if the history is empty (first message in chat)
                    const allMessages = convMessages.length > 0
                        ? convMessages
                        : [{ role: 'user', content: message }];

                    // Trim to last 2 student messages + last bot message
                    const recentStudentMsgs = allMessages.filter(m => m.role === 'user').slice(-2);
                    const recentBotMsg = [...allMessages].reverse().find(m => m.role === 'assistant');
                    const trimmedHistory = [];
                    if (recentBotMsg) trimmedHistory.push(recentBotMsg);
                    trimmedHistory.push(...recentStudentMsgs);

                    const result = await appLLMForMH.analyzeMentalHealth(trimmedHistory, detectionPrompt);

                    if (result.concernLevel !== 'no concern') {
                        await MentalHealthFlag.createMentalHealthFlag(db, {
                            studentId: req.user.userId,
                            studentName: req.user.displayName || req.user.username || 'Unknown',
                            courseId,
                            unitName,
                            message,
                            conversationContext: trimmedHistory,
                            concernLevel: result.concernLevel,
                            llmReason: result.reason
                        });
                    }
                } catch (err) {
                    console.error('Mental health detection error (non-blocking):', err);
                }
            })();
        }

        // Initialize Qdrant
        let qdrant;
        try {
            qdrant = new QdrantService();
            await qdrant.initialize();
        } catch (qdrantError) {
            console.error('❌ Qdrant initialization failed:', qdrantError.message);
            // Check if it's a connection error
            if (qdrantError.message.includes('ECONNREFUSED') || qdrantError.message.includes('fetch failed')) {
                return res.status(503).json({
                    success: false,
                    message: 'Qdrant vector database is not available. Please ensure Qdrant is running.',
                    error: 'QDRANT_CONNECTION_FAILED',
                    instructions: 'Start Qdrant with: docker run -p 6333:6333 qdrant/qdrant'
                });
            }
            // Other Qdrant errors
            return res.status(503).json({
                success: false,
                message: 'Vector database service error',
                error: qdrantError.message
            });
        }

        // Course is already loaded above for topic mapping; reuse it here for retrieval config.

        // Determine retrieval mode: Course override ? Default : False (default)
        const isAdditive = course.isAdditiveRetrieval !== undefined && course.isAdditiveRetrieval !== null
            ? !!course.isAdditiveRetrieval 
            : false;

        // Build lectureNames filter using published units only, ordered by lectures array
        const publishedLectures = (course.lectures || []).filter(l => l.isPublished).map(l => l.name);
        if (!publishedLectures.includes(unitName)) {
            return res.status(400).json({ success: false, message: 'Selected unit is not published or does not exist' });
        }

        let lectureNames = [unitName];
        if (isAdditive) {
            const order = (course.lectures || []).filter(l => l.isPublished).map(l => l.name);
            const idx = order.indexOf(unitName);
            lectureNames = idx >= 0 ? order.slice(0, idx + 1) : [unitName];
        }

        // Debug logging to verify retrieval mode and scope
        console.log(`🔎 [CHAT_RAG] RetrievalMode=${isAdditive ? 'additive' : 'single'} | Course=${courseId} | Unit=${unitName} | LectureNames=${JSON.stringify(lectureNames)}`);

        // Retrieve top chunks from Qdrant
        const searchResults = await qdrant.searchDocuments(message, { courseId, lectureNames }, 12);

        // Log summary of results by lecture to validate scope
        try {
            const lecturesHit = Array.from(new Set((searchResults || []).map(r => r.lectureName)));
            console.log(`📚 [CHAT_RAG] Retrieved ${searchResults.length} chunks from lectures: ${lecturesHit.join(', ')}`);
            // Group by document to see which files contributed
            const byDoc = {};
            for (const r of (searchResults || [])) {
                const docId = r.documentId || 'unknown-doc';
                if (!byDoc[docId]) {
                    byDoc[docId] = {
                        fileName: r.fileName || 'unknown-filename',
                        lectures: new Set(),
                        count: 0,
                        maxScore: 0
                    };
                }
                byDoc[docId].count += 1;
                byDoc[docId].lectures.add(r.lectureName);
                if (typeof r.score === 'number' && r.score > byDoc[docId].maxScore) {
                    byDoc[docId].maxScore = r.score;
                }
            }
            const docKeys = Object.keys(byDoc);
            console.log(`📄 [CHAT_RAG] Documents contributing (${docKeys.length}):`);
            for (const k of docKeys) {
                const info = byDoc[k];
                const lecturesList = Array.from(info.lectures).join(', ');
                const scoreStr = info.maxScore ? info.maxScore.toFixed(3) : 'n/a';
                console.log(`   - ${info.fileName} (id=${k}) | lectures=[${lecturesList}] | chunks=${info.count} | maxScore=${scoreStr}`);
            }
        } catch (_) {}

        // Build concise context window with citations
        const citations = searchResults.map(r => ({
            lectureName: r.lectureName,
            fileName: r.fileName,
            score: r.score
        }));
        const contextText = searchResults
            .map(r => `From ${r.lectureName} (${r.fileName}):\n${r.chunkText}`)
            .join('\n\n---\n\n');

        // Determine source attribution based on retrieved chunks
        console.log('🔍 [SOURCE_DEBUG] Retrieved chunks for source analysis:', searchResults.map(r => ({
            fileName: r.fileName,
            documentType: r.documentType,
            type: r.type,
            lectureName: r.lectureName
        })));

        let sourceAttribution;
        try {
            const sourceDownloadsEnabled = !!(course.quizSettings && course.quizSettings.allowSourceAttributionDownloads);
            sourceAttribution = await determineSourceAttribution(searchResults, unitName, sourceDownloadsEnabled);
            console.log('🔍 [SOURCE_DEBUG] Determined source attribution:', sourceAttribution);
        } catch (error) {
            console.error('🔍 [SOURCE_DEBUG] Error in source attribution:', error);
            sourceAttribution = {
                source: 'GPT',
                description: 'Generated by AI (error determining source)',
                unitName: null,
                documentType: null,
                downloadsEnabled: false,
                documents: []
            };
        }

        // Build the message to send to LLM
        let messageToSend;
        
        if (mode === 'protege') {
            messageToSend = `
CONTEXT (The correct answers):
${contextText}

INSTRUCTIONS:
Based on the Context above, act as the student described in the System Prompt.
The user just said: "${message}"
Do not explain the context to the user. Ask the user to explain it to you.`;
        } else if (req.body.isExplanationRequest) {
            // Explain mode
            messageToSend = `Use the provided course context to help explain the concept if needed.
\n\nCourse context:\n${contextText}\n\nConcept/Text to explain:\n"${message}"`;
        } else {
            // Default/Tutor mode
            messageToSend = `Use only the provided course context to answer. Cite which unit a fact came from.
\n\nCourse context:\n${contextText}\n\nStudent question: ${message}`;
        }

        // If we have conversation context (continuing a chat), use structured conversation approach
        if (conversationContext && conversationContext.conversationMessages) {
            console.log('🔄 [CHAT_CONTINUE] Using structured conversation context');

            // Build the conversation history as a single message
            let conversationHistory = '';
            conversationContext.conversationMessages.forEach(msg => {
                const speaker = msg.role === 'user' ? 'Student' : 'BiocBot';
                conversationHistory += `${speaker}: ${msg.content}\n\n`;
            });

            // Add the student's new message
            conversationHistory += `Student: ${message}`;

            // Create the full message with conversation context
            messageToSend = `Use only the provided course context to answer. Cite which unit a fact came from.

Course context:
${contextText}

Previous conversation:
${conversationHistory}`;
        }

        // Retrieve custom prompts from course object or use defaults
        let basePrompt = prompts.DEFAULT_PROMPTS.base;
        let protegePrompt = prompts.DEFAULT_PROMPTS.protege;
        let tutorPrompt = prompts.DEFAULT_PROMPTS.tutor;
        let explainPrompt = prompts.DEFAULT_PROMPTS.explain;
        let directivePrompt = prompts.DEFAULT_PROMPTS.directive;

        // Check if course has custom prompts
        if (course.prompts) {
            console.log('📝 [CHAT_API] Using course-specific prompts');
            if (course.prompts.base) basePrompt = course.prompts.base;
            if (course.prompts.protege) protegePrompt = course.prompts.protege;
            if (course.prompts.tutor) tutorPrompt = course.prompts.tutor;
            if (course.prompts.explain) explainPrompt = course.prompts.explain;
            if (course.prompts.directive) directivePrompt = course.prompts.directive;
        } else {
            console.log('[CHAT_API] Using default prompts');
        }

        // Apply Directive Mode adjustments if active
        // Apply Directive Mode adjustments if active
        if (directiveModeActive) {
            // Locked Trigger: Always prepend the topic announcement
            const lockedHeader = `\n\nCRITICAL INSTRUCTION: The student is struggling significantly with the topic "${identifiedTopic}".\nSwitch to DIRECTIVE MODE:\n`;
            
            // Configurable Strategy: Append the instructor's custom instructions
            // Append to TUTOR prompt only to avoid polluting Protege mode or Base
            tutorPrompt += lockedHeader + directivePrompt;
            
            console.log(' [CHAT_API] Appended Directive Mode instructions (Header + Strategy) to TUTOR prompt');
        }

        // Check for summary attempt via LLM if requested
        let shouldAppendReprompt = false;
        if (req.body.checkSummaryAttempt) {
            try {
                console.log('🔍 [SUMMARY_CHECK] Analyzing student message for summary attempt...');
                const summaryCheckPrompt = `Analyze the following student message. Does it attempt to summarize, recap, or explain the previous conversation? Respond with only YES or NO. Message: "${message}"`;
                
                // Use a separate, cheap LLM call (low temp, system prompt irrelevant but using base for safety)
                const summaryCheckResponse = await llmService.sendMessage(summaryCheckPrompt, {
                    temperature: 0.1,
                    maxTokens: 10,
                    systemPrompt: "You are a classifier. Respond only with YES or NO."
                });

                const isSummary = summaryCheckResponse && summaryCheckResponse.content && summaryCheckResponse.content.trim().toUpperCase().includes('YES');
                console.log(`🔍 [SUMMARY_CHECK] Result: ${isSummary ? 'YES' : 'NO'} (Raw: ${summaryCheckResponse?.content})`);

                if (!isSummary) {
                    shouldAppendReprompt = true;
                    console.log('🔍 [SUMMARY_CHECK] Student did NOT summarize -> Appending re-prompt');
                } else {
                    console.log('🔍 [SUMMARY_CHECK] Student provided summary -> No re-prompt');
                }
            } catch (err) {
                console.error('❌ [SUMMARY_CHECK] Error during check:', err);
                // Fail safe: don't annoy the user if check fails. Or default to true? 
                // Let's default to false (no re-prompt) to be safe.
            }
        }

        // In the future, we can implement conversation persistence
        let response = await llmService.sendMessage(
            messageToSend,
            {
            // Adjust response based on student mode
            temperature: mode === 'protege' ? 0.5 : 0.5,
            maxTokens: mode === 'protege' ? 32768 : 32768,
            systemPrompt: basePrompt +
                (req.body.isExplanationRequest ? explainPrompt : 
                (mode === 'protege' ? protegePrompt : tutorPrompt))
        });

        let fullContent = response && response.content ? response.content : '';

        // Detect truncation and auto-continue up to N times
        function extractFinishReason(resp) {
            try {
                return (resp && (resp.finishReason || resp.finish_reason || (resp.usage && resp.usage.finish_reason) || resp.stopReason || resp.stop_reason)) || '';
            } catch (e) { return ''; }
        }
        function isLikelyTruncated(resp, content) {
            const fr = (extractFinishReason(resp) + '').toLowerCase();
            if (fr.includes('length') || fr.includes('token')) return true;
            if (!content) return false;
            const tail = content.trim().slice(-60);
            // Check for clean sentence endings: punctuation, parenthetical unit refs, or emoji
            const endsClean = /([\.\!\?\)\u2026]|\(Unit\s+[^)]+\))\s*$/i.test(tail);
            // Only consider truncated if very long AND no clean ending AND finish reason wasn't 'stop'
            if (fr === 'stop' || fr === 'end_turn') return false;
            return !endsClean && content.length > 800;
        }

        const MAX_CONTINUATIONS = 2;
        let cont = 0;
        while (cont < MAX_CONTINUATIONS && isLikelyTruncated(response, fullContent)) {
            cont += 1;
            console.log(`⏩ [CHAT_CONTINUE] Requesting continuation ${cont}; current length=${fullContent.length}`);
            const tailSnippet = fullContent.slice(-200);
            const contPrompt = `Continue the previous answer. Do not repeat earlier content. Pick up seamlessly from here: "${tailSnippet}"`;
            const contResp = await llmService.sendMessage(contPrompt, {
                temperature: mode === 'protege' ? 0.8 : 0.6,
                maxTokens: mode === 'protege' ? 32768 : 32768,
                systemPrompt: basePrompt +
                    (mode === 'protege' ? protegePrompt : tutorPrompt)
            });
            const chunk = contResp && contResp.content ? contResp.content : '';
            console.log(`📎 [CHAT_CONTINUE] Received chunk ${cont} length=${chunk.length}`);
            if (chunk) {
                fullContent += (fullContent.endsWith('\n') ? '' : '\n') + chunk;
            }
            response = contResp;
        }

        // Append the re-prompt if the summary check determined it was needed
        if (shouldAppendReprompt) {
            fullContent += '\n\n----------------\nHey, I know you asked another question, would you like to summarize our chat again?';
        }

        // Format response for frontend
        const chatResponse = {
            success: true,
            message: fullContent,
            model: response.model,
            usage: response.usage,
            timestamp: new Date().toISOString(),
            mode: mode || 'default',
            citations,
            sourceAttribution,
            debug: {
                searchResultsCount: searchResults.length,
                avgScore: searchResults.length > 0 ? searchResults.reduce((sum, result) => sum + (result.score || 0), 0) / searchResults.length : 0,
                maxScore: searchResults.length > 0 ? Math.max(...searchResults.map(result => result.score || 0)) : 0,
                documentTypes: searchResults.map(r => ({ fileName: r.fileName, documentType: r.documentType, type: r.type, score: r.score }))
            },
            retrieval: {
                mode: isAdditive ? 'additive' : 'single',
                lectureNames
            },
            struggleState: struggleState,
            struggleDebug: {
                userExists: !!req.user,
                userId: req.user ? req.user.userId : null,
                trackerInitialized: !!localTrackerService,
                directiveModeActive: directiveModeActive,
                identifiedTopic: identifiedTopic
            }
        };

        console.log(`✅ Chat response sent successfully`);

        res.json(chatResponse);

    } catch (error) {
        console.error('❌ Error in chat endpoint:', error);

        // Provide user-friendly error messages
        let errorMessage = 'Sorry, I encountered an error processing your message.';
        let statusCode = 500;

        if (error.message.includes('OLLAMA_ENDPOINT')) {
            errorMessage = 'Ollama service is not available. Please check if Ollama is running.';
            statusCode = 503;
        } else if (error.message.includes('API key')) {
            errorMessage = 'Authentication error. Please check your API configuration.';
            statusCode = 401;
        } else if (error.message.includes('endpoint')) {
            errorMessage = 'Service endpoint is not reachable. Please check your configuration.';
            statusCode = 503;
        }

        res.status(statusCode).json({
            success: false,
            message: errorMessage,
            error: process.env.NODE_ENV === 'development' ? error.message : undefined,
            timestamp: new Date().toISOString()
        });
    }
});


/**
 * GET /api/chat/status
 * Get the current status of the LLM service
 */
router.get('/status', async (req, res) => {
    try {
        const llmService = req.app.locals.llm;

        if (!llmService) {
            return res.status(503).json({
                success: false,
                message: 'LLM service is not initialized'
            });
        }

        const status = llmService.getStatus();

        res.json({
            success: true,
            data: status
        });

    } catch (error) {
        console.error('❌ Error getting chat status:', error);

        res.status(500).json({
            success: false,
            message: 'Failed to get chat status',
            error: process.env.NODE_ENV === 'development' ? error.message : undefined
        });
    }
});



/**
 * POST /api/chat/test
 * Test the LLM connection
 */
router.post('/test', async (req, res) => {
    try {
        console.log('🧪 Testing LLM connection...');

        const llmService = req.app.locals.llm;

        if (!llmService) {
            return res.status(503).json({
                success: false,
                message: 'LLM service is not initialized'
            });
        }

        const isConnected = await llmService.testConnection();

        if (isConnected) {
            res.json({
                success: true,
                message: 'LLM connection test successful',
                provider: llmService.getProviderName(),
                timestamp: new Date().toISOString()
            });
        } else {
            res.status(503).json({
                success: false,
                message: 'LLM connection test failed',
                provider: llmService.getProviderName(),
                timestamp: new Date().toISOString()
            });
        }

    } catch (error) {
        console.error('❌ Error testing LLM connection:', error);

        res.status(500).json({
            success: false,
            message: 'Failed to test LLM connection',
            error: process.env.NODE_ENV === 'development' ? error.message : undefined,
            timestamp: new Date().toISOString()
        });
    }
});

/**
 * GET /api/chat/models
 * Get available models from the current provider
 */
router.get('/models', async (req, res) => {
    try {
        const llmService = req.app.locals.llm;

        if (!llmService) {
            return res.status(503).json({
                success: false,
                message: 'LLM service is not initialized'
            });
        }

        const models = await llmService.getAvailableModels();

        res.json({
            success: true,
            data: {
                models: models,
                provider: llmService.getProviderName(),
                timestamp: new Date().toISOString()
            }
        });

    } catch (error) {
        console.error('❌ Error getting available models:', error);

        res.status(500).json({
            success: false,
            message: 'Failed to get available models',
            error: process.env.NODE_ENV === 'development' ? error.message : undefined
        });
    }
});

/**
 * POST /api/chat/save
 * Save a chat session to the database for instructor access
 */
router.post('/save', async (req, res) => {
    try {
        const {
            sessionId,
            courseId,
            studentId,
            studentName,
            unitName,
            title,
            messageCount,
            duration,
            savedAt,
            chatData
        } = req.body;

        // Validate required fields
        if (!sessionId || !courseId || !studentId || !studentName) {
            return res.status(400).json({
                success: false,
                message: 'Missing required fields: sessionId, courseId, studentId, studentName'
            });
        }

        // Get database instance from app.locals
        const db = req.app.locals.db;
        if (!db) {
            return res.status(503).json({
                success: false,
                message: 'Database connection not available'
            });
        }

        // Save chat session to database
        const chatSessionsCollection = db.collection('chat_sessions');

        const sessionData = {
            sessionId,
            courseId,
            studentId,
            studentName,
            unitName: unitName || 'Unknown Unit',
            title: title || `Chat Session ${new Date().toLocaleDateString()}`,
            messageCount: messageCount || 0,
            duration: duration || 'Unknown',
            savedAt: savedAt || new Date().toISOString(),
            chatData: chatData || {},
            isDeleted: false, // Soft deletion flag
            createdAt: new Date()
        };

        // Insert or update the session
        await chatSessionsCollection.replaceOne(
            { sessionId: sessionId },
            sessionData,
            { upsert: true }
        );

        console.log(`Chat session saved: ${sessionId} for student ${studentName} in course ${courseId}`);

        res.json({
            success: true,
            message: 'Chat session saved successfully',
            data: {
                sessionId: sessionId,
                courseId: courseId,
                studentId: studentId
            }
        });

    } catch (error) {
        console.error('Error saving chat session:', error);
        res.status(500).json({
            success: false,
            message: 'Internal server error while saving chat session'
        });
    }
});

// ─── Practice Question: generate a new question from unit assessment questions ───
// In-memory store for generated practice questions (keyed by a temp ID)
// so we never send the correct answer to the client
const practiceQuestionStore = new Map();

router.post('/practice-question', async (req, res) => {
    try {
        const { courseId, unitName, topic } = req.body;

        if (!courseId || !unitName) {
            return res.status(400).json({ success: false, message: 'courseId and unitName are required.' });
        }

        const db = req.app.locals.db;

        // Pull assessment questions for this unit
        const allQuestions = await CourseModel.getAssessmentQuestions(db, courseId, unitName);

        if (!allQuestions || allQuestions.length === 0) {
            return res.json({
                success: true,
                noQuestions: true,
                message: 'There are no questions to practice right now.'
            });
        }

        // Pick up to 6 random questions as seed material
        const shuffled = [...allQuestions].sort(() => 0.5 - Math.random());
        const seedQuestions = shuffled.slice(0, 6);

        // Build a prompt for the LLM to generate a NEW question
        const seedText = seedQuestions.map((q, i) => {
            let entry = `${i + 1}. [${q.questionType}] ${q.question}`;
            if (q.options && typeof q.options === 'object') {
                entry += '\n   Options: ' + Object.entries(q.options).map(([k, v]) => `${k}. ${v}`).join(' | ');
            }
            entry += `\n   Answer: ${q.correctAnswer}`;
            if (q.explanation) entry += `\n   Explanation: ${q.explanation}`;
            return entry;
        }).join('\n\n');

        const generationPrompt = prompts.buildPracticeQuestionPrompt(seedText, topic);

        const llmService = req.app.locals.llm;

        const llmResponse = await llmService.sendMessage(generationPrompt, {
            temperature: 0.7,
            response_format: { type: "json_object" }
        });

        // Parse the generated question
        let generated;
        try {
            const jsonStart = llmResponse.content.indexOf('{');
            const jsonEnd = llmResponse.content.lastIndexOf('}') + 1;
            if (jsonStart !== -1 && jsonEnd !== 0) {
                generated = JSON.parse(llmResponse.content.substring(jsonStart, jsonEnd));
            } else {
                throw new Error('No JSON found in LLM response');
            }
        } catch (parseErr) {
            console.error('❌ Failed to parse practice question JSON:', parseErr);
            return res.status(500).json({ success: false, message: 'Failed to generate a practice question. Please try again.' });
        }

        // Validate required fields
        if (!generated.questionType || !generated.question || !generated.correctAnswer) {
            return res.status(500).json({ success: false, message: 'Generated question was incomplete. Please try again.' });
        }

        // Store correct answer server-side, keyed by a temp ID
        const practiceId = `pq_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
        practiceQuestionStore.set(practiceId, {
            correctAnswer: generated.correctAnswer,
            explanation: generated.explanation || '',
            question: generated.question,
            questionType: generated.questionType,
            createdAt: Date.now()
        });

        // Send to client WITHOUT correctAnswer
        const clientQuestion = {
            practiceId,
            questionType: generated.questionType,
            question: generated.question
        };
        if (generated.questionType === 'multiple-choice' && generated.options) {
            clientQuestion.options = generated.options;
        }

        res.json({ success: true, data: clientQuestion });

    } catch (error) {
        console.error('❌ Error generating practice question:', error);
        res.status(500).json({ success: false, message: 'Failed to generate practice question.' });
    }
});

// ─── Check Practice Answer ───
router.post('/check-practice-answer', async (req, res) => {
    try {
        const { practiceId, studentAnswer, studentName } = req.body;

        if (!practiceId || !studentAnswer) {
            return res.status(400).json({ success: false, message: 'practiceId and studentAnswer are required.' });
        }

        const stored = practiceQuestionStore.get(practiceId);
        if (!stored) {
            return res.status(404).json({ success: false, message: 'Practice question not found or expired. Please generate a new one.' });
        }

        const { correctAnswer, explanation, question, questionType } = stored;

        if (questionType === 'short-answer') {
            // Use LLM evaluation for short-answer
            const llmService = req.app.locals.llm;

            const result = await llmService.evaluateStudentAnswer(
                question,
                studentAnswer,
                correctAnswer,
                questionType,
                studentName || 'Student'
            );

            return res.json({
                success: true,
                data: {
                    correct: result.correct,
                    feedback: result.feedback,
                    correctAnswer: correctAnswer,
                    explanation: explanation
                }
            });
        } else {
            // MCQ or TF — simple string comparison
            const correct = studentAnswer.trim().toLowerCase() === correctAnswer.trim().toLowerCase();
            const feedback = correct
                ? 'Correct! Well done.'
                : `Incorrect. The correct answer is ${correctAnswer}.`;

            return res.json({
                success: true,
                data: {
                    correct,
                    feedback: feedback + (explanation ? ` ${explanation}` : ''),
                    correctAnswer: correctAnswer
                }
            });
        }

    } catch (error) {
        console.error('❌ Error checking practice answer:', error);
        res.status(500).json({ success: false, message: 'Failed to check answer.' });
    }
});

module.exports = router;
